In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # or "1", "0,1", etc.

import torch
print(torch.cuda.device_count())  # should show 1 if restricted

1

In [2]:
import pandas as pd
import evaluate
from sentence_transformers import SentenceTransformer
from tqdm import tqdm
from pathlib import Path
import json

/home/halim/.virtualenvs/experiment/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
def get_generated_questions(file_path):
    try:
        df = pd.read_json(file_path, lines=True, orient='records')
        contents = [item.replace("\nPertanyaan:  ", "").split("\n\nJawaban:")[0] for item in df['content']]
    except:
        df = pd.read_json(file_path, lines=True, orient='records')
        contents = df['generated_text']
    return contents

bleu = evaluate.load("bleu")
rouge = evaluate.load('rouge')

def compute_score(generated_list_of_content, task, dataset='squad'):
    if dataset == 'squad':
        reference = pd.read_json("~/Documents/halim/few-shot-aqg/dev_with_examples.jsonl", lines=True, orient='records')
        reference = reference[reference['is_impossible'] == False].reset_index(drop=True)
        if task == 'qg':
            reference = reference['question']
        elif task == 'ae':
            reference = reference['answer']
        else:
            return "the task can only be qg or ae"
    else:
        with open('../data/tydiqa-preprocesed-eval.json', 'r') as f:
            data = json.load(f)
        reference = [item['question'] for item in data]
        print(reference)
    


    bleu_score = bleu.compute(predictions=generated_list_of_content, references=reference)
    precision_keys = ['bleu1', 'bleu2', 'bleu3', 'bleu4']
    for i, key in enumerate(precision_keys):
        bleu_score[key] = bleu_score['precisions'][i]    
    del bleu_score['precisions']
    rouge_score = rouge.compute(predictions=generated_list_of_content, references=reference)

    model = SentenceTransformer("all-MiniLM-L6-v2")
    
    bert_scores = [model.similarity(model.encode(each), model.encode(reference[i]))[0] 
                                    for i, each in tqdm(
                                        enumerate(generated_list_of_content), 
                                        total=len(generated_list_of_content)
                                    )]
    average_bert_scores = {"bert_score": sum(bert_scores)/len(bert_scores)}

    return {**bleu_score, 
            **{k: float(v) for k, v in rouge_score.items()}, 
            **{k: float(v) for k, v in average_bert_scores.items()}}

In [4]:
list_files = sorted(list(Path(".").glob("*.jsonl")))
list_files = [item for item in list_files if 'question-generation' in item.name and 'SQuAD-id' in item.name]
list_files

[PosixPath('question-generation-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('question-generation-v1-12-SQuAD-id.jsonl'),
 PosixPath('question-generation-v1-42-SQuAD-id.jsonl'),
 PosixPath('question-generation-v1-72-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-12-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-42-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-72-SQuAD-id.jsonl')]

In [5]:
result_df = pd.DataFrame([compute_score(get_generated_questions(item), 'qg') for item in list_files])
result_df['model'] = [item.name.split("question-generation-")[1].replace(".jsonl","") for item in list_files]
# variants = [item.name.split("few_")[1].replace(".jsonl","") for item in list_files]
# variants_type = [
#     "randmix" if "rand_ex_mix" in x
#     else "randfix" if "rand_ex_same" in x
#     else "similar" if "sim_ex_question" in x
#     else None
#     for x in variants
# ]

# variants_shot = [
#     "3" if "3shots" in x
#     else "5" if "5shots" in x
#     else None
#     for x in variants
# ]

# result_df['variant_type'] = variants_type
# result_df['variant_shot'] = variants_shot

100%|██████████| 5928/5928 [00:35<00:00, 165.55it/s]
100%|██████████| 5928/5928 [00:36<00:00, 164.52it/s]
100%|██████████| 5928/5928 [00:29<00:00, 198.41it/s]
100%|██████████| 5928/5928 [00:21<00:00, 271.45it/s]
100%|██████████| 5928/5928 [00:19<00:00, 306.71it/s]
100%|██████████| 5928/5928 [00:18<00:00, 312.22it/s]
100%|██████████| 5928/5928 [00:18<00:00, 316.74it/s]
100%|██████████| 5928/5928 [00:20<00:00, 285.06it/s]
100%|██████████| 5928/5928 [00:20<00:00, 291.13it/s]
100%|██████████| 5928/5928 [00:18<00:00, 313.90it/s]
100%|██████████| 5928/5928 [00:19<00:00, 311.54it/s]
100%|██████████| 5928/5928 [00:18<00:00, 316.12it/s]
100%|██████████| 5928/5928 [00:18<00:00, 315.28it/s]
100%|██████████| 5928/5928 [00:18<00:00, 315.36it/s]

In [6]:
result_df

,bleu,brevity_penalty,length_ratio,translation_length,reference_length,bleu1,bleu2,bleu3,bleu4,rouge1,rouge2,rougeL,rougeLsum,bert_score,model
0,0.009273,1.0,7.413128,443268,59795,0.039037,0.012700,0.005470,0.002726,0.088447,0.028123,0.076500,0.076441,0.459429,idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-...
1,0.009113,1.0,7.606271,454817,59795,0.039024,0.012631,0.005368,0.002606,0.087629,0.028107,0.076009,0.075952,0.459092,idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD...
2,0.009113,1.0,7.606271,454817,59795,0.039024,0.012631,0.005368,0.002606,0.087629,0.028107,0.076009,0.075952,0.459092,idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuA...
3,0.010152,1.0,6.079689,363535,59795,0.046326,0.013870,0.005838,0.002832,0.111454,0.035335,0.097641,0.097592,0.483151,idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-...
4,0.056095,1.0,1.140564,68200,59795,0.258416,0.065824,0.031521,0.018466,0.229359,0.078028,0.208757,0.208785,0.593942,idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-...
5,0.055210,1.0,1.162907,69536,59795,0.255479,0.065306,0.031259,0.017816,0.228868,0.077193,0.208636,0.208568,0.592840,idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD...
6,0.166386,1.0,1.027561,61443,59795,0.445844,0.203098,0.116059,0.072929,0.445518,0.226297,0.409140,0.409287,0.717021,idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuA...
7,0.018563,1.0,3.820286,228434,59795,0.087631,0.023447,0.010449,0.005531,0.170819,0.057480,0.146377,0.146329,0.559849,idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id...
8,0.061397,1.0,2.538055,151763,59795,0.191931,0.077752,0.040784,0.023347,0.380914,0.189458,0.339269,0.339567,0.686163,v1-12-SQuAD-id
9,0.148141,1.0,1.155046,69066,59795,0.405366,0.181048,0.102727,0.063882,0.439574,0.224219,0.401069,0.401423,0.714617,v1-42-SQuAD-id
10,0.138450,1.0,1.240773,74192,59795,0.380027,0.169870,0.095868,0.059371,0.437200,0.224505,0.397766,0.397926,0.714147,v1-72-SQuAD-id
11,0.158762,1.0,1.077582,64434,59795,0.430006,0.194561,0.110598,0.068660,0.443226,0.225797,0.406300,0.406329,0.715989,v2-12-SQuAD-id
12,0.157685,1.0,1.079773,64565,59795,0.430605,0.192950,0.109260,0.068105,0.443965,0.224493,0.406127,0.406079,0.716355,v2-42-SQuAD-id
13,0.164336,1.0,1.045606,62522,59795,0.441844,0.201170,0.114574,0.071617,0.447463,0.228012,0.410028,0.410189,0.717680,v2-72-SQuAD-id

In [7]:
list_files_tydiqa = sorted(list(Path(".").glob("*.jsonl")))
list_files_tydiqa = [item for item in list_files_tydiqa if 'question-generation' in item.name and 'TydiQA-id' in item.name]
list_files_tydiqa

[PosixPath('question-generation-idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-yesprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-qg-yesprefix-yesprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('question-generation-idt5-base-qaqg-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('question-generation-v1-12-TydiQA-id.jsonl'),
 PosixPath('question-generation-v1-42-TydiQA-id.jsonl'),
 PosixPath('question-generation-v1-72-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-12-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-42-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-72-TydiQA-id.jsonl')]

In [8]:
result_df_tydiqa = pd.DataFrame([compute_score(get_generated_questions(item), 'qg', 'tydiqa') for item in list_files_tydiqa])
result_df_tydiqa['model'] = [item.name.split("question-generation-")[1].replace(".jsonl","") for item in list_files_tydiqa]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 321.49it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 320.82it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 321.58it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 327.61it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 329.52it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 328.38it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 328.68it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 327.45it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 321.38it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 326.08it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 325.00it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 318.42it/s]

['Siapakah yang menemuka benua Amerika ?', 'Dimanakah letak Donggala ?', 'Siapa bapak Teknik industri?', 'Kapan Penghulu Rasyid meninggal ?', 'seberapa luas kah samudera pasifik?', 'apakah yang dimaksud denga geisha ?', 'Kapan Bank BCA mengeluarkan kartu debit?', 'Dimana kantor pusat General Motors?', 'Berapa luas kota Blitar?', 'Siapa yang menciptakan serial manga Crows?', 'siapakah karakter utama serial anime dan manga Eyeshield 21?', 'Siapakah yang merumuskan naskah proklamasi ?', 'Bagaimanakah sistem pemerintahan di Jepang ?', 'kapankah Gerakan Pemuda Ansor didirikan?', 'Apakah yang diceritakan dalam The Years of Rice and Salt?', 'apakah pendidikan terakhir  Budi Susilo Soepandji?', 'dimanakah letak Cekungan Tarim?', 'terbuat dari apakah Genta ?', 'Siapakah R.L. Stine?', 'Siapakah yang menggagas Determinisme biologis?', 'Apakah nama lagu kebangsaan Jepang?', 'Dimana Konsili Kartago diadakan?', 'berapakah luas Bendung Katulampa?', 'Apa nama ilmiah tumbuhan kaktus ?', 'Kapan perahu pertama dibuat ?', 'dari manakah tari angin mamiri berasal?', 'Kapan Yekaterina I lahir ?', 'Kapan Banjir Besar Gun-Yu pertama kali terjadi ?', 'kapankah presiden soeharto meninggal dunia?', 'Kapan Johann Ludwig Tieck lahir ?', 'Dimana letak Museum Anak Kolong Tangga?', 'apakah yang dimaksud dengan Hiragana?', 'siapakah pendiri klub Leicester City?', 'Apa lambang dari perusahaan Paramount Pictures?', 'Apa nama pesawat terbang pertama yang dimiliki Indonesia?', 'Siapakah raja pertama kerajaan Yordania ?', 'tahun berapakah Universitas Islam Negeri Sumatera Utara didirikan?', 'kapankah perum PNRI didirikan?', 'Apakah yang dimaksud dengan korvet ?', 'Di negara manakah Moehammad Joesoef Ronodipoero menjadi duta besar?', 'Bagaimana Porifera berkembangbiak?', 'Dari mana asal kata Bodas ?', 'apa nam mata uang thailand ?', 'Kapan The Best Damn Thing dirilis?', 'Sejak kapan Yakuza mulai muncul di Jepang ?', 'apakah nama mata uang jepang?', 'siapakah pendiri Proton?', 'siapakah Grandmaster termuda di indonesia?', 'apakah kabupaten terluas di Provinsi Jawa Timur?', 'Apakah gereja terbesar di Swedia?', 'Kapan Walt Disney Animation Studios berdiri ?', 'Apa nama alat penyimpan audio pertama ?', 'Kapan István III lahir ?', 'Siapa sutradara film Sleeping Beauty?', 'siapakah karakter utama Serial anime dand manga Eyeshield 21?', 'Apa maksud kata Whataboutisme?', 'Apa nama bandara di Penang?', 'Siapakah nama istri Sir Alexander Chapman "Alex" Ferguson ?', 'Apakah arti kata Mandala ?', 'Berapakah luas negara wales ?', 'dimanakah  Dipati Ukur meninggal?', 'kapan lionel messi masuk barcelona?', 'apakah yang definisi psikopatologi?', 'Kapan Sense and Sensibility dirilis?', 'siapakah sutradara film Jailangkung pertama?', 'apakah yang di maksud dengan masyarakat?', 'apakah warna ular Bakas?', 'Berapa luas Museum Louvre?', 'Kapan Sekolah Regina Pacis didirikan?', 'Kapankah TVRI berdiri ?', 'berapakah luas Kabupaten Banggai?', 'siapakah orang tua Ferdinand VII?', 'berapakah jumlah populasi di seoul?', 'kapankah Kekaisaran Bizantium berakhir?', 'Apa yang dimaksud dengan daerah otonom?', "Apakah seni Islam pertama di Baitul Qur'an?", 'apa yang dimaksud dengan komunikasi satu arah?', 'Kapan sekuel Percy Jackson difilmkan ?', 'Berapa lama periode Sengoku berlangsung?', 'dimanakah kantor pusat perusahaan Sampoerna?', 'Apakah maksud istilah Shengnü?', 'Apa nomor atom Klorin?', 'kapankah Bebop mulai dipopulerkan?', 'Berapa tinggi rata rata pohon pace?', 'adakah mikroorganisme yang bisa bertahan di planet mars?', 'Dimanakah letak Manchuria ?', 'apakah yang di maksud dengan Manga Shonen?', 'Kapan Sakurajima pertama kali erupsi?', 'apakah kekuatan Sonic the Hedgehog?', 'Apakah buku pertama dari novel "The Chronicles of Narnia"?', 'Apakah kepanjangan dari HIV ?', 'Kapan Bob Dylan lahir?', 'Berapa luas Kabupaten Donggala?', 'Apakah yang dimaksud dengan dewa dalam kepercayaan Hindu ?', 'Apakah bahan bakar mesin jet?', 'Kapan Yan Xishan diangkat menjadi panglima perang Tiongkok ?', 'siapa pelopor ilmu mekanika kuantum?', 'siapakah nama pemeran the beast dalam serial Beauty and the Beast?', 'Kapan WrestleMania XXVII pertama tayang?', 'Berapa besar kapal Galiung Manila?', 'kapankah HUT kota Balikpapan?', 'kapan Naguib Mahfouz dilahirkan?', 'Kapan film animasi Monster,Inc dirilis?', 'Siapakah istri Djamaludin Malik?', 'Dimanakah letak Galilea?', 'Siapa pendiri PT Scooter Victory Inter Part?', 'siapakah aktivis Feminisme indonesia yang pertama?', 'Kapan album Hollywood Dreams dirilis?', 'siapakah yang membangun Gedung Reichstag?', 'Apa tugas utama malaikat Israfil menurut Islam ?', 'Apakah smartphone pertama yang diproduksi realme?', 'Kapan Komputer mikro mulai dikembangkan ?', 'Apakah pengertian matronimik?', 'Siapakah Basuki Tjahaja Purnama?', 'Kapan Raja  Ataulf menikah ?', 'Apakah kuliner yang terkenal dari daerah surabaya ?', 'Dimanakah letak Desa Karang kancana?', 'Kenapa Hamzah bin Abdul-Muththalib dijuluki singa Allah ?', 'Berapa lama proses pembangunan Masjid Wazir Khan?', 'siapakah penemu televisi?', 'dimanakah letak Lecce ?', 'Siapakah presiden pertama Singapura ?', 'Apa tugas Malaikat Mikhael dalam Islam?', 'apakah yang dimaksud dengan gagasan?', 'dari manakah asal pohon Bidara ?', 'Siapakah anak Bunda Maria Penolong Abadi?', 'apakah penyebab kematian Wong Agung Wilis?', 'di kota manakah Sapta Darma pertama kali muncul?', 'kapankah boneka Barbie pertama kali diciptakan?', 'Apa pengertian dari antibiotik ?', 'Jenis Protista apakah yang dapat membahayakan manusia?', 'berapakah luas benua Republik Demokratik Somali?', 'Kapan Liu Ju meninggal?', 'Dimana letak Orléans?', 'Ada berapa kandidat dalam Pemilu Jerman 2017?', 'Apakah makanan Thopha saccata?', 'Kapan kereta api Orient Express pertama dibuka?', 'Apa undang-undang yang mengatur tentang pornografi di Indonesia ?', 'Kapan Arung Palakka lahir?', 'Berapa luas kota Atambua?', 'Apa itu Wangsa Plantagenet?', 'siapakah yang menciptakan boneka Barbie?', 'apakah nama mata uang rusia?', 'Kapan Kinetoskop diciptakan ?', 'Siapakah sultan pertama Brunei Darussalam ?', 'apakah yang di maksud dengan feodal?', 'apakah pendidikan terakhir Mochamad Fadjroel Rachman?', 'seberapa luaskah samudera atlantik?', 'Kapan agama katolik masuk ke Indonesia ?', 'Kapan Helloween dibentuk ?', 'Dari manakah asal Mr. Raden Mas Sartono?', 'Siapa presiden Republik Ghana pertama?', 'Ada berapakah serial Cardcaptor Sakura?', 'Berapa jumlah pasukan yang mempertahankan Roma?', 'Kapankah Gempa bumi dan tsunami Sulawesi 2018 terjadi ?', 'Apa itu karapas ?', 'Apakah kepanjangan dari Nekolim?', 'Kapan Yuchi Jingde lahir?', 'Kapan Katolik masuk ke Indonesia ?', 'Siapa ibu Baudouin I ?', 'Siapakah yang terlibat dalam Pertempuran Badar?', 'Apa nama badan PBB yang mengurus tentang perlindungan anak ?', 'Apa yang dimaksud dengan neokonservatif ?', 'Apa definisi dari frekuensi ?', 'Apa itu hipertropi otot?', 'Kapan Petrus Lombardus lahir?', 'Siapa yang menciptakan robot pertama kali ?', 'dimanakah letak samudera pasifik?', 'Apa yang dimaksud dengan pornoaksi ?', 'Apakah nomor atom Iodin?', 'apakah spesies ubur-ubur yang terbesar?', 'Kapan Radio Republik Indonesia berdiri ?', 'berapakah luas Takalar ?', 'Dimanakah letak objek wisata Sendang Bidadari?', 'Kapan Komando Divisi IX Banteng dibentuk?', 'mata uang apakah yang di gunakan di korea selatan?', 'Apa itu  Sport Utility Vehicle?', 'berapakah luas  Candi Ratu Boko?', 'dimanakah Squidward Tentacles bekerja?', 'dimanakah letak danau baikal?', 'Apakah nama tempat wisata yang terkenal di Jepang ?', 'dari manakah asalsuku-bangsa Sasak?', 'Apakah definisi dari Gempa Tektonik ?', 'Kapan Fender Musical Instruments Corporation berdiri ?', 'Dari manakah wangsa Komnenos berasal ?', 'apakah yang dimaksudkan dengan Tsarevich?', 'Kapan Festival Film Indonesia pertama diadakan?', 'Apakah nama bidang ilmu yang mempelajari morfem ?', 'Apakah ajaran yang dipercayai Suku Dayak Hindu Budha Bumi Segandu Indramayu?', 'Kapan HSBC Holdings PLC didirikan?', 'Apakah film pertama Alexa Ellesse Vega?', 'Apakah yang dimaksud dengan Urochordata?', 'dimanakah letak Manokwari?', 'Apakah yang dimaksud dengan emosi ?', 'Apakah nama kopi yang terkenal dari Aceh ?', 'Apa nama mata uang Lebanon ?', 'Kapan Insiden Honnoji terjadi ?', 'Apa nama mata uang Uzbekistan ?', 'Apakah warna bendera Myanmar ?', 'Kapan industri penerbangan mulai beroperasi di Indonesia ?', 'Dimana Siauw Giok Tjhan  lahir ?', 'Dimana Dr. Henry Walton Jones, Jr mengajar arkeologi?', 'Berapa lama Pelemparan di Praha terjadi?', 'Di siaran tv apa Hikmah Fajar ditayangkan?', 'Apakah nama stasiun kereta api di Bekasi?', 'Kapan Pemberontakan Para Budak terjadi ?', 'Dimana Insiden Honnoji  terjadi ?', 'Apakah tujuan utama upacara adat Kuangkay dilakukan?', 'Kapan konsep Melayu Raya dibentuk?', 'Siapakah sultan pertama Kesultanan Aceh?', 'Apa warna bendera Meksiko ?', 'Apa yang dimaksud dengan genin dalam manga naruto ?', 'apa manfaat sekam?', 'Cabe apa yang digunakan untuk membuat sambal Balado?', 'Berapakah berat U-511?', 'Apa kepanjangan dari KASAD?', 'berapakah tinggi Megatron?', 'Kapan Kekaisaran Bulgaria Pertama didirikan?', 'siapakah yang mencptakan Ide 4 sehat 5 sempurna pertama kali?', 'siapakah gubernur pertama Provinsi Sulawesi Tengah?', 'Kapan Heinrich Luitpold Himmler diangkat menjadi komandan Schutzstaffel Jerman?', 'Apakah definis dari Finansial ?', 'Berapa berat Mesin kepung?', 'mikroorganisme apa kah yang baik untuk tubuh manusia?', 'Kapan musik DJ pertama kali muncul di dunia ?', 'Berapa lama Aleksander Yaneus menjadi raja?', 'Kapan Su Dingfang lahir?', 'Mengapa sindikat Yakuza disebut mafia Jepang?', 'Apakah jenis belatung yang digunakan untuk Terapi belatung?', 'siapakah ayah dari Aleksander III?', 'Apa nama kopi yang terkenal dari daerah Aceh ?', 'siapakah orang tua Manuel Luis Quezón y Molina?', 'Tahun berapa Birmingham Zulus mulai aktif?', 'Ada berapa serial film Fifty Shades of Grey?', 'dimanakah Nabi Muhammad SAW dikuburkan?', 'Apakah yang dimaksud dengan luar angkasa ?', 'Dimanakah rumah igloo biasa ditemukan?', 'siapakah penemu aljabar?', 'Apakah definisi dari femininitas?', 'dimanakah kantor pusat Djisamsoe?', 'Bagaiaman sistem pemerintahan di Jepang ?', 'Kapan Oskar-Heinz “Pritzl” Bär pertama kali ikut perang ?', 'kapankah May Day pertama kali dilakukan?', 'Dimana Su Dingfang lahir?', 'Apa agama mayoritas penduduk korea ?', 'siapakah istri George Herbert Walker Bush?', 'Siapakah istri dari George H. W. Bush?', 'siapakah pencetus  standar ukuran kertas internasional?', 'Kapan sistem Ina-TEWS pertama digunakan?', 'Apakah jenis Masakan Kirgizstan yang paling terkenal?', 'Siapakah Perdana menteri Israel sebelum Yitzhak Shamir?', 'mata uang apakah yang digunakan di jepang?', 'Apakah fungsi utama pesawat Hercules?', 'Kapan BlackBerry mulai masuk ke Indonesia ?', 'Apakah nama pulau terbesar Kepulauan Hawaii?', 'Berapa biaya produksi film Fences ?', 'Apakah pengertian dari entitas?', 'Apa isi surat deuteropauline?', 'Apa yang dimaksud dengan membran sel ?', 'Dari negara mana Hergé berasal ?', 'berapakah luas Abu Dhabi?', 'Kapan boyband B.A.P dibentuk ?', 'Apa tujuan utama Asosiasi Televisi Swasta Indonesia didirikan?', 'dimanakah LTE pertama kali diciptakan?', 'apakah nama penghargaan tertinggi di bidang jurnalisme?', 'apa yang dimaksud komunikasi dua arah?', 'Kapan  Charles Maurras lahir ?', 'Kapan tayangan pertama acara Hikmah Fajar?', 'apa pengertian Filsafat?', 'berapakah luas  Masjid Tua Palopo?', 'Apa itu reaktor nuklir?', 'Darimanakah asal Marc Márquez?', 'Kapan PDRM dibentuk ?', 'siapakah presiden russia pada tahun 2012?', 'Apa itu Penghargaan Nobel?', 'Apakah bahan bakar sinyal asap?', 'di tim apakah Marc Márquez Alenta mendapatkan  gelar juara dunia kelas 125cc pertama kali?', 'siapakah teman baik karakter SpongeBob SquarePants?', 'Siapakah Bapak Binaraga Modern?', 'Dimana Pelemparan di Praha terjadi?', 'Kapan Pieter Willem Botha lahir ?', 'Dimanakah letak Universitas Tadulako ?', 'Kapan Philip Heinrich Christoph Hofman mulai menjadi misionaris Belanda?', 'Apa nama lembaga pemerintah yang menangani pemberantasan narkotika ?', 'siapakah yang menemukan Ötzi?', 'apakah yang di maksud dengan endomembran?', 'Dimana Gereja Yesus Kristus?', 'Siapa ayah Baudouin I ?', 'Dimana Philip Heinrich Christoph Hofman lahir?', 'apakah pendidikan terakhir Ida Bagus Mantra?', 'Siapa Teruo Nakamura?', 'Kapan  Rudi Garcia mulai menjadi manajer sepak bola ?', 'Dimanakah letak Danzig ?', 'Apa yang dimaksud dengan Maharani?', 'Dimanakah proklamasi dibacakan ?', 'siapakah yang menciptakan Lampu lalu lintas ?', 'Berapa jumlah fakultas di Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Gereja Bethany didirikan?', 'siapakah yang memimpin Kongres Pemuda Indonesia I?', 'Kapan Bon Jovi berdiri ?', 'Kapan Kumandang Sastra mulai disiarkan ?', 'Apa yang dimaksud dengan Jambore pramuka?', 'berapakah jumlah episode/seri Go-Tōbun no Hanayome?', 'berapakah jumlah pulau di kepulauan Krakatau?', 'Kapan Pelemparan di Praha terjadi?', 'Siapa karakter utama dalam The Castle of Cagliostro?', 'Dimanakah tumbuhan kaktus sering dijumpai ?', 'Kapan Kubilai Khan lahir?', 'siapakah yang menciptakan Istilah Genosida?', 'mata uang apakah yang digunakan di Iran?', 'Siapa pendiri Institut Leimena?', 'Apakah kepercayaan masyarakat Korea?', 'siapapresiden pertama indonesia?', 'Siapakah perdana menteri pertama Pakistan ?', 'Di umur berapa Michael Trent Reznor mulai belajar musik?', 'Kapan Kitab Yesaya ditulis ?', 'Dimanakah aliran Sungai Asahan berakhir ?', 'berapakah luas Kota Pasuruan?', 'Apa itu Teknologi Komunikasi?', 'Dimanakah letak Timur Dekat Kuno?', 'Apakah maksud Shamanisme Korea?', 'apakah mamalia yang terbesar didunia ?', 'Dimanakah fosil Homo floresiensis ditemukan?', 'siapakah sutradara film merantau?', 'Kapan Sunan Ampel meninggal?', 'Apa tugas utama malaikat Mikail menurut Islam ?', 'siapakah nama karakter antagonis utama di dalam Avatar: The Last Airbender?', 'Apakah bahan utama pembuatan aspartam?', 'Siapa ketua fraksi Partai Aliansi Liberal dan Demokrat untuk Eropa?', 'kapankah kapal pertama diciptakan?', 'apakah nama alat musik yang digemari Squidward Tentacles?', 'dimanakah kantor pusat Kemenperin RI?', 'Siapakah Kubilai Khan?', 'Apakah agama Paul F. Knitter?', 'Berapa luas pulau Belitung ?', 'Kapan Hulagu Khan meninggal ?', 'apakah yang di maksud dengan membran ?', 'tahun berapakah Kesultanan Aceh didirikan?', 'Apakah warna bendera Meksiko ?', 'Apa yang dimaksud dengan semiconductor?', 'Apa yang dimaksud komunikasi visual?', "Siapa pendiri agama Bahá'í?", 'Dimana letak Kensington ?', 'siapakah jenderal pertama TNI ?', 'Apa kota terbesar di Papua Barat?', 'Kapan  Kritik atas Nalar Murni diterbitkan?', 'Kapan Petar Segrt ditunjuk menjadi pelatih kepala PSM Makassar?', 'Siapa juara Grand Prix Amerika Serikat 2005?', 'Berapa luas pulau Jamaika?', 'Dimana letak Balai Kota DKI Jakarta?', 'Kapan acara realitas Mamamia pertama kali masuk di Indonesia?', 'Apakah bahasa mayoritas suku Bulgar?', 'Dimana letak Montenegro?', 'Kapan Mayor PNB Djalaludin Tantu bergabung dengan TNI ?', 'Apakah penyebab utama Pengeboman pasar Tentena 2005?', 'Dimana letak Aquitania?', 'Kapankah tiongkok menjadi negara republik ?', 'Kapan buku Stardust diterbitkan di Inggris?', 'Siapakah presiden Turkmenistan pertama ?', 'Bahasa apa yang digunakan dalam Kitab Yesus bin Sirakh?', 'Dari mana asal kata Bhagawadgita?', 'Berapa jumlah tim sepak bola di Jerman?', "Siapa artis wanita pemeran utama dalam Eiffel... I'm in Love?", 'Apakah yang dimaksud dengan Membran vakuola?', 'Abad keberapakah zaman feodal Jepang?', 'Apa mayoritas agama penduduk Libanon ?', 'siapakah penerus Asyurbanipal?', 'Kapan Museum Goedang Ransoem dibangun ?', 'siapakah ketua Perum LKBN pertama?', 'apakah karya terakhir beethoven?', 'Kapan PT Broadband Multimedia Tbk berubah menjadi First Media ?', 'Dimana Petrus Lombardus meninggal?', 'dari manakah istilah genosida berasal?', 'Tahun berapa orde lama berakhir?', 'berapakah jumlah kecamatan Kabupaten Nabire?', 'Kapan PT bus Damri didirikan?', 'Berapa luas Las Vegas?', 'Siapa yang merumuskan naskah proklamasi Indonesia?', 'Kapan Pieter Willem Botha menjabat sebagai perdana menteri ?', 'Kapan Tarekat Qodiriyah wa Naqsyabandiyah berdiri ?', 'tahun berapakah The Greatest Showman dirilis?', 'Apakah yang dimaksud dengan Transgender?', 'Kapan Perusahaan Jawatan Kereta Api didirikan?', 'Apakah yang dimaksud dengan Pecinan ?', 'Kapan Empire Earth dirilis ?', 'apakah Film pertama yang diperankan oleh Putri Marino?', 'Dimana letak daerah Malta di Eropa ?', 'Apakah nama universitas terbesar di Hamburg?\\', 'Berapa lama Prof. Dr. Gerrit A. Siwabessy menjadi Menteri Kesehatan Republik Indonesia?', 'Siapakah Dr. H. Shofwan Karim Elha?', 'Kapan Need for Speed: \u200b\u200bPayback dirilis?', 'siapakah PM/President pertama Republik India?', 'berapa lamakah zaman Orde Lama berlangsung?', 'Kapan R.M.A.A. Koesoemo Oetoyo diangkat menjadi bupati ?', 'Kapan Johnny Hiromu Kitagawa lahir?', 'Kapan Pembantaian Westerling terjadi ?', 'Kapan ponsel Blackberry pertama kali rilis ?', 'Apa yang dimaksud dengan Gerakan kepanduan?', 'berapakah luas Kepulauan Marshall?', 'Dari manakah adal club CONMEBOL?', 'mata uang apakah yang digunakan di brazil?', 'Siapakah pembawa acara Hikmah Fajar?', 'Apakah peran dewa wisnu dalam kepercayaan Hindu ?', 'apakah yang dimaksud dengan polimer ?', 'Siapakah pemimpin Khilafah pertama ?', 'Dimana Oskar-Heinz “Pritzl” Bär lahir ?', 'Apa definisi dari wilayah ?', 'Berapakah panjang pantai Pesisir Selatan?', 'Apa penyebab letusan Gunung St. Helens pada 18 Mei, 1980?', 'Dimana Johnny Hiromu Kitagawa lahir?', 'Berapa frekuensi Radio Pelita Kasih?', 'apakah nama Gereja tertua di Jakarta?', 'Apakah perusahaan pertama tempat David Mackenzie Ogilvy bekerja?', 'Apa yang dimaksud dengan kota Metropolitan?', 'Apakah kandungan dalam susu kambing ?', 'Kapan BlackBerry diciptakan ?', 'Dimanakah letak Universitas Leiden ?', 'Apa yang dimaksud dengan Depo lokomotif ?', 'Kapan Masjid Shah  dibangun ?', 'Siapa pendiri Dailymotion ?', 'dimanakah letak Suaka margasatwa Muara Angke ?', 'Siapa penerbit buku Kompas Emas?', 'Dimanakah letak negara Angola ?', 'apakah penghargaan tertinggi dalam bidang Jurnalisme?', 'Siapa pendiri Institut Teknologi Sepuluh Nopember Surabaya?', 'Kapan Joseph Muscat lahir ?', 'berapkah jumlah album The Rain?', 'Apa yang dimaksud dengan Sang Tiga Dewata Murni?', 'apakah yang dimaksud dengan simbiosis ?', 'Perselisihan apakah yang terjadi pada masa pemerintahan Yelizaveta ?', 'apakah bahan utama untuk menciptakan Reglet?', 'Apakah baterai yang digunakan dalam Jam tangan ponsel?', 'Kapan Padre Pio lahir?', 'Apa penyebab kematian Islam Abduganiyevich Karimov?', 'Apakah fungsi utama tumbuhan jarak ?', 'Siapa pendiri PT. Kharisma Starvision Plus?', 'Kapan aksara Lontara digunakan dalam adat masyrakat bugis ?', 'Dimana Raja  Ataulf meninggal?', 'Apa itu agama samawi?', 'Kapan Sekte Rinzai di jepang berdiri ?', 'apakah arti dari heraldik ?', 'Apa ciri khas dari kebudayaan Neolitik?', 'Apakah novel kedua dari Trilogi Rajawali?', 'Apa yang dimaksud dengan membran ?', 'kapankah SpongeBob pertama kali dirilis?', 'Apa yang dimaksud dengan frekuensi ?', 'apakah yang dimaksud dengan Tarekat religius Katolik?', 'Dimana Arung Palakka lahir?', 'Pada zaman apakah aksara baji digunakan?', 'berapakah luas Pulau Enggano?', 'Apakah nama rumah adat suku Banjar?', 'siapakah wanita yang di nikahi Barrack Obama?', 'Kapan Lothar II lahir?', 'Siapakah presiden wanita pertama di Filipina ?', 'Kapan tari Breakdance muncul ?', 'Kapan  Francis Fukuyama lahir ?', 'berapakah jumlah kecamatan di Kabupaten Majalengka?', 'Kapan organisasi Muhammadiyah berdiri ?', 'Siapakah anak dari Margarita dari Navarra?', 'Apa definisi sederhana dari antibiotika ?', 'dari manakah tari haka berasal?', 'Berapakah jumlah korban jiwa tsunami Sulawesi 2018?', "Apakah ajaran inti agama Bahá'í?", 'siapakah Dewa Wisnu menurut agama Hindu?', 'Apakah nama pesaw

100%|██████████| 565/565 [00:01<00:00, 326.53it/s]

In [9]:
result_df_tydiqa

,bleu,brevity_penalty,length_ratio,translation_length,reference_length,bleu1,bleu2,bleu3,bleu4,rouge1,rouge2,rougeL,rougeLsum,bert_score,model
0,0.008023,1.000000,1.449090,5337,3683,0.046468,0.010897,0.003963,0.002065,0.061819,0.017201,0.060309,0.060283,0.351681,idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA...
1,0.003552,1.000000,1.427641,5258,3683,0.041841,0.007671,0.001896,0.000262,0.056569,0.013367,0.055176,0.054866,0.338775,idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQ...
2,0.075385,1.000000,1.308173,4818,3683,0.181196,0.086292,0.055957,0.036912,0.208614,0.118236,0.206429,0.206001,0.495986,idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id...
3,0.200307,0.957017,0.957915,3528,3683,0.472222,0.241309,0.155129,0.108565,0.421266,0.245741,0.418435,0.418485,0.712640,idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA...
4,0.187002,0.913076,0.916644,3376,3683,0.489336,0.239772,0.149154,0.100535,0.417818,0.231831,0.413089,0.413219,0.716007,idt5-base-qaqg-qg-yesprefix-noprepend-42-TydiQ...
5,0.207185,0.989355,0.989411,3644,3683,0.484358,0.243910,0.155529,0.104669,0.448582,0.250748,0.440564,0.440567,0.739036,idt5-base-qaqg-qg-yesprefix-yesprepend-42-Tydi...
6,0.224833,0.941613,0.943253,3474,3683,0.510363,0.271915,0.179608,0.130410,0.455641,0.279247,0.451643,0.451329,0.741827,idt5-base-qaqg-yesprefix-noprepend-42-TydiQA-i...
7,0.182778,1.000000,1.038284,3824,3683,0.457374,0.222154,0.133630,0.082198,0.438945,0.246476,0.431507,0.431785,0.735816,v1-12-TydiQA-id
8,0.106722,1.000000,1.354331,4988,3683,0.309142,0.129098,0.072836,0.044627,0.342852,0.177484,0.335083,0.335450,0.671329,v1-42-TydiQA-id
9,0.194075,1.000000,1.019549,3755,3683,0.461784,0.231348,0.142476,0.093204,0.437138,0.248171,0.430286,0.430126,0.729055,v1-72-TydiQA-id
10,0.164738,1.000000,1.077926,3970,3683,0.419647,0.199706,0.117606,0.074725,0.400294,0.221060,0.395017,0.394791,0.708480,v2-12-TydiQA-id
11,0.182239,1.000000,1.052403,3876,3683,0.443240,0.213833,0.132192,0.088033,0.419148,0.237563,0.411689,0.412411,0.722082,v2-42-TydiQA-id
12,0.157077,1.000000,1.080641,3980,3683,0.403769,0.189165,0.112864,0.070619,0.386113,0.207978,0.377528,0.377668,0.700332,v2-72-TydiQA-id