In [1]:
import pandas as pd
import json
from pathlib import Path
from evaluate import load

/home/halim/.virtualenvs/experiment/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
list_files = list(Path('.').glob('answer-extraction-*.jsonl'))
list_files.sort()
list_files

[PosixPath('answer-extraction-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-yesprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-v1-12-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v1-12-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v1-42-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v1-42-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v1-72-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v1-72-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-12-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-12-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-42-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-42-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-72-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-72-TydiQA-id.jsonl')]

In [3]:
list_files_squad = [f for f in list_files if 'SQuAD' in f.name]
list_files_tydiqa = [f for f in list_files if 'TydiQA' in f.name]

In [4]:
list_files_squad

[PosixPath('answer-extraction-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuAD-id-checkpoint-15000.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id-checkpoint-23475.jsonl'),
 PosixPath('answer-extraction-v1-12-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v1-42-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v1-72-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-12-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-42-SQuAD-id.jsonl'),
 PosixPath('answer-extraction-v2-72-SQuAD-id.jsonl')]

In [5]:
list_files_tydiqa

[PosixPath('answer-extraction-idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-noprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-qg-yesprefix-yesprepend-42-TydiQA-id-checkpoint-2855.jsonl'),
 PosixPath('answer-extraction-idt5-base-qaqg-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705.jsonl'),
 PosixPath('answer-extraction-v1-12-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v1-42-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v1-72-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-12-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-42-TydiQA-id.jsonl'),
 PosixPath('answer-extraction-v2-72-TydiQA-id.jsonl')]

In [6]:
# SQuAD is_possible answer formation
squad_eval = pd.read_json('../data/squad-dev.jsonl', lines=True)
squad_eval = squad_eval[squad_eval['is_impossible'] == False]

In [7]:
squad_eval

,context,question,answer_alternatives,answer,is_impossible,id
0,Bangsa Normandia (Norman: Nourmands; Prancis: ...,Di negara apa Normandia berada?,"[Perancis, Perancis, Perancis, Perancis]",[Perancis],False,56ddde6b9a695914005b9628
1,Bangsa Normandia (Norman: Nourmands; Prancis: ...,Kapan Normandia di Normandia?,"[Abad 10 dan 11, di abad ke-10 dan ke-11, Abad...",[10 dan ke],False,56ddde6b9a695914005b9629
2,Bangsa Normandia (Norman: Nourmands; Prancis: ...,Dari negara mana asal Norse?,"[Denmark, Islandia, dan Norwegia, Denmark, Isl...","[Denmark, Islandia dan Norwegia]",False,56ddde6b9a695914005b962a
3,Bangsa Normandia (Norman: Nourmands; Prancis: ...,Siapa pemimpin Norse?,"[Rollo, Rollo, Rollo, Rollo]",[Rollo],False,56ddde6b9a695914005b962b
4,Bangsa Normandia (Norman: Nourmands; Prancis: ...,Abad berapa pertama kali Normandia mendapatkan...,"[Abad ke-10, paruh pertama abad ke-10, 10, 10]",[abad ke-10],False,56ddde6b9a695914005b962c
...,...,...,...,...,...,...
11864,"Gaya pon memiliki padanan metrik, yang lebih j...",Apa istilah metrik yang kurang digunakan darip...,"[kekuatan kilogram, kekuatan pound, kilogram-f...",[kilogram-force],False,5737aafd1c456719005744fb
11865,"Gaya pon memiliki padanan metrik, yang lebih j...",Seperti apa kekuatan kilogram yang kadang-kada...,"[kilopond, kilopond, kilopond, kilopond, kilop...",[kilopond],False,5737aafd1c456719005744fc
11866,"Gaya pon memiliki padanan metrik, yang lebih j...",Apakah satuan massa yang sangat jarang digunak...,"[siput, siput metrik, siput metrik, siput metr...",[siput],False,5737aafd1c456719005744fd
11867,"Gaya pon memiliki padanan metrik, yang lebih j...",Apa yang jarang menggunakan istilah satuan kek...,"[tidur, tidur, tidur, tidur, tidur]",[kip],False,5737aafd1c456719005744fe
11868,"Gaya pon memiliki padanan metrik, yang lebih j...",Berapa satuan gaya yang jarang digunakan sama ...,"[sthène, sthène, sthène, sthène, sthène]",[sthène],False,5737aafd1c456719005744ff

In [8]:
grouped_squad_eval_on_context = squad_eval.groupby('context', sort=False).agg(
    {'answer': 'sum',
     }
    ).reset_index()
grouped_squad_eval_on_context

,context,answer
0,Bangsa Normandia (Norman: Nourmands; Prancis: ...,"[Perancis, 10 dan ke, Denmark, Islandia dan No..."
1,"Dinasti Norman memiliki dampak politik, budaya...","[William Sang Penakluk, Richard I, Katolik]"
2,"Nama Inggris ""Normans"" berasal dari kata Pranc...","[Viking, abad ke-9]"
3,"Selama abad ke-10, serangan yang awalnya merus...","[911, Raja Charles III, Seine]"
4,"Sebelum kedatangan Rollo, populasinya tidak be...",[Rollo]
...,...,...
1199,"di mana massa benda, adalah kecepatan benda da...","[pusat lintasan melengkung, tegak lurus, sentr..."
1200,Gaya konservatif yang bekerja pada sistem tert...,"[kinetik, potensial, energi mekanis netto, per..."
1201,"Untuk skenario fisik tertentu, tidak mungkin u...","[forces, gradien potensi, gesekan, nonkonserva..."
1202,Hubungan antara kekuatan nonkonservatif makros...,"[mekanika statistik, nonconservative forces, n..."
1203,"Gaya pon memiliki padanan metrik, yang lebih j...","[kilogram-force, kilopond, siput, kip, sthène]"

In [9]:
for item in list_files_squad:
    item_data = pd.read_json(item, lines=True)['generated_text']
    item_data_raw = [subitem.split(' [SEP] ') for subitem in item_data]
    item_data_non_dupli = [list(set(subitem.split(' [SEP] '))) for subitem in item_data]
    grouped_squad_eval_on_context[f'raw-{item.name.replace("answer-extraction-","").replace(".jsonl","")}'] = item_data_raw
    grouped_squad_eval_on_context[f'unique-{item.name.replace("answer-extraction-","").replace(".jsonl","")}'] = item_data_non_dupli
    
grouped_squad_eval_on_context

,context,answer,raw-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475,unique-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475,raw-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475,unique-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475,raw-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475,unique-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475,raw-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475,unique-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475,...,raw-v1-42-SQuAD-id,unique-v1-42-SQuAD-id,raw-v1-72-SQuAD-id,unique-v1-72-SQuAD-id,raw-v2-12-SQuAD-id,unique-v2-12-SQuAD-id,raw-v2-42-SQuAD-id,unique-v2-42-SQuAD-id,raw-v2-72-SQuAD-id,unique-v2-72-SQuAD-id
0,Bangsa Normandia (Norman: Nourmands; Prancis: ...,"[Perancis, 10 dan ke, Denmark, Islandia dan No...","[Normandia, Normandia, Normandia, Rollo, Carol...","[Carolingian, Rollo, Normandia]","[Normandia, Normanni, Normandia, Rollo, Caroli...","[Carolingian, Rollo, Normandia, Normanni]","[Normandia, Normanni, Normandia, Rollo, Caroli...","[Carolingian, Rollo, Normandia, Normanni]","[abad ke-10 dan ke-11, Normandia, Normandia, R...","[Carolingian, Rollo, Normandia, abad ke-10 dan...",...,"[Normandia, Normandia, Normandia, Rollo, Carol...","[Carolingian, Rollo, Normandia]","[Normandia, Normandia, Normandia, Normanni, Ro...","[Rollo, Normandia, Normanni]","[Normandia, Denmark, Islandia dan Norwegia]","[Normandia, Denmark, Islandia dan Norwegia]","[Normandia, Normandia, abad ke-10 dan ke-11, R...","[Normandia [SEP, abad ke-10 dan ke-11, Denmark...","[Normandia, abad ke-10 dan ke-11, Rollo, Denma...","[Rollo, Normandia, Denmark, Islandia dan Norwe..."
1,"Dinasti Norman memiliki dampak politik, budaya...","[William Sang Penakluk, Richard I, Katolik]","[Kristen, Gallo-Romantis, Norman, Normaund ata...","[Gallo-Romantis, Norman, Normaund atau Norman ...","[semangat bela diri mereka, Gallo-Romantis, No...","[Gallo-Romantis, semangat bela diri mereka, No...","[semangat bela diri mereka, Gallo-Romantis, No...","[Gallo-Romantis, semangat bela diri mereka, No...","[semangat bela diri mereka, Gallo-Romantis, Ka...","[Kadipaten Normandia, Gallo-Romantis, semangat...",...,"[Kristen, Gallo-Romantis, Richard I, 1066, Boh...","[Richard I, Gallo-Romantis, Kristen, 1066, Boh...","[Kristen, Gallo-Romantis, Norman, Normaund ata...","[Kerajaan Antiokhia di Levant, ke Skotlandia d...","[Norman, Normaund atau Norman French, Pertempu...","[Norman, Normaund atau Norman French, Pertempu...","[Normandia, Normandia, Richard I dari Normandi...","[Kerajaan Antiokhia di Levant, Pertempuran Has...","[Norman, Normaund atau Norman French adalah ba...","[Norman, Normaund atau Norman French adalah ba..."
2,"Nama Inggris ""Normans"" berasal dari kata Pranc...","[Viking, abad ke-9]","[Normans / Normanz, Normant, normand Perancis ...","[Old Low Franconian Nortmann ""Northman"" atau l...","[Normans / Normanz, Normant, normand Perancis ...","[Normant, normand Perancis modern,, Normans / ...","[Normans / Normanz, Normant, normand Perancis ...","[Normant, normand Perancis modern,, Normans / ...","[Normans / Normanz, Normant, normand Perancis ...","[Normant, normand Perancis modern,, Normans / ...",...,"[Normans / Normanz, Normant, normand Perancis ...","[Old Low Franconian Nortmann ""Northman"" atau l...","[Normans / Normanz, Normant, Old Low Franconia...","[Nortmannus, Normannus, atau Nordmannus, Old L...","[Normans / Normanz, Nortmannus, Normannus, ata...","[Normans / Normanz, Nortmannus, Normannus, ata...","[Normans / Normanz, Normant,normand Perancis m...","[Normant,normand Perancis modern,, Normans / N...","[Normans / Normanz, Old Low Franconian Nortman...","[Old Low Franconian Nortmann ""Northman"" atau l..."
3,"Selama abad ke-10, serangan yang awalnya merus...","[911, Raja Charles III, Seine]","[911, Raja Charles III dari Francia Barat, Rol...","[911, bekas kerajaan Frank di Neustria, Raja C...","[911, Raja Charles III dari Francia Barat dan ...","[911, bekas kerajaan Frank di Neustria, strukt...","[911, Raja Charles III dari Francia Barat dan ...","[911, bekas kerajaan Frank di Neustria, strukt...","[911, Raja Charles III dari Francia Barat dan ...","[911, bekas kerajaan Frank di Neustria, Raja C...",...,"[wanita lokal dan properti pribadi, 911, Raja ...",[Raja Charles III dari Francia Barat dan pengu...,"[911, Kadipaten Normandia, Raja Charles III da...","[Neustria, 911, Kadipaten Normandia, Raja Char...","[911, Raja Charles III dari Francia Barat dan ...","[bekas kerajaan Frank di Neustria, Raja Charle...","[911, bekas kerajaan Frank di Neustria, Kadipa...","[bekas kerajaan Frank di Neustria, Kadipaten N...","[911, Raja Charles III dari Francia Barat dan ...","[bekas kerajaan Frank di Neustria, Raja Charle..."
4,"Sebelum kedatangan Rollo, populasinya tidak be...",[Rollo],"[Picardy atau Île-de-France, 880-an, Normandia...",[Normandia dan bagian-bagian pantai Atlantik t...,"[Picardy atau Île-de-France, 880-an, Normandia...",[Normandia dan bagian-bagian pantai Atlantik t...,"[Picardy atau Île-de-France, 880-an, Normandia...",[Normandia dan bagian-bagian pantai Atlantik t...,"[Picardy atau Île-de-France, yang dianggap ""Fr...",[Normandia dan bagian-bagian pantai Atlantik t...,...,"[Picardy atau <0xC3>le-de-France, yang diangga...",[dibagi antara koloni di timur (Roumois dan Pa...,"[Picardy atau <0xC3>le-de-France, yang diangga...",[pemukim Viking telah mulai berdatangan di tah...,"[Picardy atau <0xC3>le-de-France, yang diangga...",[di sekitar lembah Seine rendah dan di barat d...,"[Picardy atau <0xC3>le-de-France, yang diangga...","[Denmark, Norwegia, Norse-Gaels, Orkney Viking...","[Picardy atau <0xC3>le-de-France, yang diangga...","[Denmark, Norwegia, Norse-Gaels, Orkney Viking..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1199,"di mana massa benda, adalah kecepatan benda da...","[pusat lintasan melengkung, tegak lurus, sentr...",[kecepatan benda dan jarak ke pusat lintasan m...,[gaya sentripetal yang tidak seimbang yang dir...,[kecepatan benda dan jarak ke pusat lintasan m...,[gaya sentripetal yang tidak seimbang yang dir...,[kecepatan benda dan jarak ke pusat lintasan m...,[gaya sentripetal yang tidak seimbang yang dir...,[Apa yang dapat dipecahkan menjadi komponen ya...,[Apa yang dapat dipecahkan menjadi komponen ya...,...,[kecepatan benda dan jarak ke pusat lintasan m...,[gaya sentripetal yang tidak seimbang yang dir...,"[massa benda, adalah kecepatan benda dan jarak...",[gaya sentripetal yang tidak seimbang yang dir...,"[massa benda, adalah kecepatan benda dan jarak...","[massa benda, adalah kecepatan benda dan jarak...","[Gaya tangensial, gaya radial, gaya radial]","[gaya radial, Gaya tangensial]","[massa benda, adalah kecepatan benda dan jarak...","[massa benda, adalah kecepatan benda dan jarak..."
1200,Gaya konservatif yang bekerja pada sistem tert...,"[kinetik, potensial, energi mekanis netto, per...",[gaya konservatif yang bekerja pada sistem ter...,[arah dan jumlah aliran air dapat dipertimbang...,"[hanya antara bentuk kinetik atau potensial., ...",[arah dan jumlah aliran air dapat dipertimbang...,"[hanya antara bentuk kinetik atau potensial., ...",[arah dan jumlah aliran air dapat dipertimbang...,[Gaya konservatif yang bekerja pada sistem ter...,[energi mekanis netto dikonservasi setiap kali...,...,[Gaya konservatif yang bekerja pada sistem ter...,[energi mekanis netto dikonservasi setiap kali...,"[antara bentuk kinetik atau potensial., energi...",[arah dan jumlah aliran air dapat dipertimbang...,[Gaya konservatif yang bekerja pada sistem ter...,[Gaya konservatif yang bekerja pada sistem ter...,[gaya konservatif yang bekerja pada sistem ter...,[gaya konservatif yang bekerja pada sistem ter...,[Gaya konservatif yang bekerja pada sistem ter...,[Gaya konservatif yang bekerja pada sistem ter...
1201,"Untuk skenario fisik tertentu, tidak mungkin u...","[forces, gradien potensi, gesekan, nonkonserva...","[karena gradien potensi, pertimbangan makrofis...",[masing-masing kekuatan makroskopik ini adalah...,"[memodelkan gaya karena gradien potensi., pert...",[masing-masing kekuatan makroskopik ini adalah...,"[memodelkan gaya karena gradien potensi., pert...",[masing-masing kekuatan makroskopik ini adalah...,"[Untuk skenario fisik tertentu, tidak mungkin ...","[Untuk skenario fisik tertentu, tidak mungkin ...",...,"[karena gradien potensi., model gaya yang tida...","[kekuatan konservatif, model gaya yang tidak t...","[gradien potensi, rata-rata statistik makro da...",[masing-masing kekuatan makroskopik ini adalah...,"[Untuk skenario fisik tertentu, tidak mungkin ...","[Untuk skenario fisik tertentu, tidak mungkin ...",[tidak mungkin untuk memodelkan gaya karena gr...,[tidak mungkin untuk memodelkan gaya karena gr...,"[Untuk skenario fisik tertentu, tidak mungkin ...","[Untuk skenario fisik tertentu, tidak mungkin ..."
1202,Hubungan antara kekuatan nonkonservatif makros...,"[mekanika statistik, nonconservative forces, n...","[kekuatan konservatif mikroskopis, perawatan r...","[mengubah energi internal sistem,, perawatan r...",[kekuatan nonkonservatif makroskopik dan kekua...,"[mengubah energi internal sistem,, perawatan r...",[kekuatan nonkonservatif makroskopik dan kekua...,"[mengubah energi internal sistem,, perawatan r...",[kekuatan nonkonservatif makroskopik dan kekua...,[transformasi energi dalam sistem tertutup dar...,...,[kekuatan nonkonservatif makroskopik dan kekua...,"[mengubah energi internal sistem, perpindahan ...",[kekuatan nonkonservatif makroskopik dan kekua...,"[perawatan rinci dengan mekanika statistik., e...",[kekuatan nonkonservatif makroskopik dan kekua...,[kekuatan nonkonservatif makroskopik dan kekua...,[gaya nonkonservatif makroskopik dan kekuatan ...,[gaya nonkonservatif makroskopik dan kekuatan ...,[gaya nonkonservatif makroskopik bertindak unt...,[gaya nonkonservatif makroskopik bertindak unt...
1203,"Gaya pon memiliki padanan metrik, yang lebih j...","[kilogram-force, kilopond, siput, kip, sthène]","[gaya kilogram (kgf) (kadang-kadang kilopond),...","[sthène, yang setara dengan 1000 N, dan kip, y...","[gaya kilogram (kgf) (kadang-kadang kilopond),...","[pengekspresian berat pesawat, daya dorong jet...","[gaya kilogram (kgf) (kadang-kadang kilopond),...","[pengekspresian berat pesawat, daya dorong jet...","[Gaya pon memiliki padanan metrik, yang lebih ...","[sthène, yang setara dengan 1000 N, dan kip, y...",...,"[padanan metrik, gaya kilogram (kgf) (kadang-k...","[gaya kilogram (kgf) (kadang-kadang kilopond),...","[gaya kilogram (kgf) (kadang-kadang kilopond),...",[gaya kilogram (kgf) (kadang-kadang mug atau h...,"[Gaya pon memiliki padanan metrik, yang lebih ...","[Gaya pon memiliki padanan metrik, yang lebih ...","[Gaya pon memiliki padanan metrik, yang lebih ...","[Gaya pon memiliki padanan metrik, yang lebih ...","[gaya kilogram (kgf) (kadang-kadang kilopond),...","[gaya kilogram (kgf) (kadang-kadang kilopond),..."

In [10]:
with open('../data/tydiqa-preprocesed-eval.json', 'r') as f:
    tydiqa_eval = json.load(f)

grouped_tydiqa_eval_on_context = pd.DataFrame(tydiqa_eval).groupby('context', sort=False).agg(
    {'answer': 'sum',
     }
    ).reset_index()

grouped_tydiqa_eval_on_context

,context,answer
0,Kolumbus bukanlah orang pertama yang tiba di A...,orang-orang Viking dari Eropa Utara
1,Kabupaten Donggala (English: Donggala Regency)...,"provinsi Sulawesi Tengah, Indonesia4275,08km²4..."
2,Awal mula Teknik Industri dapat ditelusuri dar...,Frederick Winslow Taylor
3,Penghulu Rasyid (lahir di desa Telaga Itar tah...,15 Desember 1861
4,Samudra Pasifik atau Lautan Teduh (dari bahas...,"179,7 juta km²di antara Asia dan Australia di ..."
...,...,...
509,"Nepal nyaris berbentuk segi empat, dengan pa...",147.181 km²
510,Radang (English: inflammation) adalah respon ...,respon dari suatu organisme terhadap patogen d...
511,Studi hubungan internasional sebagai teori sud...,1939
512,"Dalam melaksanakan kegiatan belajar-mengajar, ...",29095m²
513,Ikan pari manta (Manta birostris) adalah salah...,3 ton

In [11]:
for item in list_files_tydiqa:
    item_data = pd.read_json(item, lines=True)['generated_text']
    item_data_raw = [subitem.split(' [SEP] ') for subitem in item_data]
    item_data_non_dupli = [list(set(subitem.split(' [SEP] '))) for subitem in item_data]
    grouped_tydiqa_eval_on_context[f'raw-{item.name.replace("answer-extraction-","").replace(".jsonl","")}'] = item_data_raw
    grouped_tydiqa_eval_on_context[f'unique-{item.name.replace("answer-extraction-","").replace(".jsonl","")}'] = item_data_non_dupli
    
grouped_tydiqa_eval_on_context

,context,answer,raw-idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA-id-checkpoint-5705,unique-idt5-base-qaqg-ae-noprefix-noprepend-42-TydiQA-id-checkpoint-5705,raw-idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705,unique-idt5-base-qaqg-ae-yesprefix-noprepend-42-TydiQA-id-checkpoint-5705,raw-idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id-checkpoint-5705,unique-idt5-base-qaqg-noprefix-noprepend-42-TydiQA-id-checkpoint-5705,raw-idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA-id-checkpoint-2855,unique-idt5-base-qaqg-qg-noprefix-noprepend-42-TydiQA-id-checkpoint-2855,...,raw-v1-42-TydiQA-id,unique-v1-42-TydiQA-id,raw-v1-72-TydiQA-id,unique-v1-72-TydiQA-id,raw-v2-12-TydiQA-id,unique-v2-12-TydiQA-id,raw-v2-42-TydiQA-id,unique-v2-42-TydiQA-id,raw-v2-72-TydiQA-id,unique-v2-72-TydiQA-id
0,Kolumbus bukanlah orang pertama yang tiba di A...,orang-orang Viking dari Eropa Utara,[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[siapakah orang pertama yang masuk ke benua Am...,[siapakah orang pertama yang masuk ke benua Am...,...,[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11],[abad ke 11]
1,Kabupaten Donggala (English: Donggala Regency)...,"provinsi Sulawesi Tengah, Indonesia4275,08km²4...","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]",[berapakah luas Kabupaten Donggala?],[berapakah luas Kabupaten Donggala?],...,"[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]","[4275,08km2]"
2,Awal mula Teknik Industri dapat ditelusuri dar...,Frederick Winslow Taylor,[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Siapa yang menemukan ilmu Economic Science?],[Siapa yang menemukan ilmu Economic Science?],...,[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Frederick Winslow Taylor],[Apakah frasa untuk menggambarkan bidang ini d...,[Apakah frasa untuk menggambarkan bidang ini d...,[apakah yang dimaksud dengan Teori Ekonomi?],[apakah yang dimaksud dengan Teori Ekonomi?]
3,Penghulu Rasyid (lahir di desa Telaga Itar tah...,15 Desember 1861,[1815],[1815],[1815],[1815],[1815],[1815],[Kapan Penghulu Rasyid lahir?],[Kapan Penghulu Rasyid lahir?],...,[1815],[1815],[salah seorang di antara sejumlah ulama Islam ...,[salah seorang di antara sejumlah ulama Islam ...,[1815],[1815],[1815],[1815],[1815],[1815]
4,Samudra Pasifik atau Lautan Teduh (dari bahas...,"179,7 juta km²di antara Asia dan Australia di ...","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]",[Berapa luas Samudra Pasifik?],[Berapa luas Samudra Pasifik?],...,"[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]","[179,7 juta km2]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,"Nepal nyaris berbentuk segi empat, dengan pa...",147.181 km²,[147.181 km2],[147.181 km2],[147.181 km2],[147.181 km2],[147.181 km2],[147.181 km2],[berapakah luas negara Nepal?],[berapakah luas negara Nepal?],...,[147.181 km2],[147.181 km2],[147.181 km2],[147.181 km2],[145.181 km2],[145.181 km2],[147.181 km2],[147.181 km2],[145.181 km2],[145.181 km2]
510,Radang (English: inflammation) adalah respon ...,respon dari suatu organisme terhadap patogen d...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[Apa itu Radang?],[Apa itu Radang?],...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...,[respon dari suatu organisme terhadap patogen ...
511,Studi hubungan internasional sebagai teori sud...,1939,[1939],[1939],[1939],[1939],[1939],[1939],[Kapan ilmu hubungan internasional pertama kal...,[Kapan ilmu hubungan internasional pertama kal...,...,[1939],[1939],[1939],[1939],[1939],[1939],[The Twenty Years' Crisis],[The Twenty Years' Crisis],[Twenty Years' Crisis],[Twenty Years' Crisis]
512,"Dalam melaksanakan kegiatan belajar-mengajar, ...",29095m²,[28997m2],[28997m2],[28997m2],[28997m2],[28997m2],[28997m2],[Berapa luas SMK Negeri 1 Cikampek?],[Berapa luas SMK Negeri 1 Cikampek?],...,[28997m2],[28997m2],[28997m2],[28997m2],[28997m2],[28997m2],[berapakah luas SMK Negeri 1 Cikampek?],[berapakah luas SMK Negeri 1 Cikampek?],[Berapa luas SMK Negeri 1 Cikampek?],[Berapa luas SMK Negeri 1 Cikampek?]
513,Ikan pari manta (Manta birostris) adalah salah...,3 ton,[ujung sirip dada ke ujung sirip lainnya menca...,[ujung sirip dada ke ujung sirip lainnya menca...,[Ikan pari manta],[Ikan pari manta],[apakah nama spesies ikan pari terbesar di dun...,[apakah nama spesies ikan pari terbesar di dun...,[Berapa luas ikan pari manta?],[Berapa luas ikan pari manta?],...,[Ikan pari manta],[Ikan pari manta],[Ikan pari manta],[Ikan pari manta],[salah satu spesies ikan pari terbesar di dunia],[salah satu spesies ikan pari terbesar di dunia],[salah satu spesies ikan pari terbesar di dunia],[salah satu spesies ikan pari terbesar di dunia],"[9,1 meter]","[9,1 meter]"

In [12]:
target_columns = sorted([item for item in grouped_squad_eval_on_context.columns if '-' in item]) 
target_columns_tydiqa = sorted([item for item in grouped_tydiqa_eval_on_context.columns if '-' in item])
target_columns

['raw-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475',
 'raw-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475',
 'raw-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475',
 'raw-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475',
 'raw-idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-id-checkpoint-15000',
 'raw-idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD-id-checkpoint-15000',
 'raw-idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuAD-id-checkpoint-15000',
 'raw-idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id-checkpoint-23475',
 'raw-v1-12-SQuAD-id',
 'raw-v1-42-SQuAD-id',
 'raw-v1-72-SQuAD-id',
 'raw-v2-12-SQuAD-id',
 'raw-v2-42-SQuAD-id',
 'raw-v2-72-SQuAD-id',
 'unique-idt5-base-qaqg-ae-noprefix-noprepend-42-SQuAD-id-checkpoint-8475',
 'unique-idt5-base-qaqg-ae-yesprefix-noprepend-42-SQuAD-id-checkpoint-8475',
 'unique-idt5-base-qaqg-ae-yesprefix-yesprepend-42-SQuAD-id-checkpoint-8475',
 'unique-idt5-base-qaqg-noprefix-noprepend-42-SQuAD-id-checkpoint-23475',
 'unique-idt5-base-qaqg-qg-noprefix-noprepend-42-SQuAD-id-checkpoint-15000',
 'unique-idt5-base-qaqg-qg-yesprefix-noprepend-42-SQuAD-id-checkpoint-15000',
 'unique-idt5-base-qaqg-qg-yesprefix-yesprepend-42-SQuAD-id-checkpoint-15000',
 'unique-idt5-base-qaqg-yesprefix-noprepend-42-SQuAD-id-checkpoint-23475',
 'unique-v1-12-SQuAD-id',
 'unique-v1-42-SQuAD-id',
 'unique-v1-72-SQuAD-id',
 'unique-v2-12-SQuAD-id',
 'unique-v2-42-SQuAD-id',
 'unique-v2-72-SQuAD-id']

In [13]:
from typing import List
import numpy as np
from sentence_transformers import SentenceTransformer, util
from tqdm import tqdm

# Load model once globally for efficiency
bert_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

def ngitung(predicted: List[str], actual: List[str]):
    """
    Compute QA-style Exact Match (EM), Precision, Recall, F1, number of predictions,
    and BERT semantic similarity score.
    """
    # Normalize
    predicted = [p.lower().strip() for p in predicted]
    actual = [a.lower().strip() for a in actual]

    # Pad shorter list
    max_len = max(len(predicted), len(actual))
    preds = predicted + [''] * (max_len - len(predicted))
    refs = actual + [''] * (max_len - len(actual))

    em_scores, f1_scores, precision_scores, recall_scores, bert_sims = [], [], [], [], []

    # Compute embeddings once
    embeddings_pred = bert_model.encode(preds, convert_to_tensor=True)
    embeddings_ref = bert_model.encode(refs, convert_to_tensor=True)

    for i, (p, r) in tqdm(enumerate(zip(preds, refs)), total=len(refs)):
        # Exact Match
        em = int(p == r)
        em_scores.append(em)

        # Token-level metrics
        p_tokens = p.split()
        r_tokens = r.split()
        common_tokens = set(p_tokens) & set(r_tokens)
        if not common_tokens:
            precision = recall = f1 = 0
        else:
            precision = len(common_tokens) / len(p_tokens) if p_tokens else 0
            recall = len(common_tokens) / len(r_tokens) if r_tokens else 0
            f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0
        precision_scores.append(precision)
        recall_scores.append(recall)
        f1_scores.append(f1)

        # BERT similarity (cosine)
        bert_sim = util.cos_sim(embeddings_pred[i], embeddings_ref[i]).item()
        bert_sims.append(bert_sim)

    return {
        'num_predictions': len(predicted),
        'exact_match': np.mean(em_scores) ,
        'precision': np.mean(precision_scores) ,
        'recall': np.mean(recall_scores) ,
        'f1': np.mean(f1_scores) ,
        'bert_similarity': np.mean(bert_sims)   
    }

In [14]:
import pandas as pd

# Initialize a list to hold the results
results_list = []

for col in target_columns:
    predicted_list = grouped_squad_eval_on_context[col].explode().tolist()
    actual_list = grouped_squad_eval_on_context['answer'].explode().tolist()
    
    scores = ngitung(predicted=predicted_list, actual=actual_list)
    
    # Append results as a dict
    results_list.append({
        'column': col,
        'num_predictions': scores['num_predictions'],
        'exact_match': scores['exact_match'],
        'precision': scores['precision'],
        'recall': scores['recall'],
        'f1': scores['f1'],
        'bert_score': scores['bert_similarity']
    })

# Convert list of dicts into a DataFrame
scores_df = pd.DataFrame(results_list)

# Optional: format the numbers to 2 decimal places
scores_df[['exact_match', 'precision', 'recall', 'f1', 'bert_score']] = scores_df[['exact_match', 'precision', 'recall', 'f1', 'bert_score']].round(4)

100%|██████████| 5928/5928 [00:00<00:00, 25073.14it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26306.20it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26716.12it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26934.33it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27297.94it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27359.73it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27183.10it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26764.95it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26515.62it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26605.37it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26451.23it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26873.28it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27246.34it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27233.89it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26553.91it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26818.93it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26820.67it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26784.09it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27403.87it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27207.96it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27440.56it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26783.11it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26916.05it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26957.72it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26798.76it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27114.06it/s]
100%|██████████| 5928/5928 [00:00<00:00, 27167.56it/s]
100%|██████████| 5928/5928 [00:00<00:00, 26918.96it/s]

In [15]:
import pandas as pd

# Initialize a list to hold the results
results_list = []

for col in target_columns_tydiqa:
    predicted_list = grouped_tydiqa_eval_on_context[col].explode().tolist()
    actual_list = grouped_tydiqa_eval_on_context['answer'].explode().tolist()
    
    scores = ngitung(predicted=predicted_list, actual=actual_list)
    
    # Append results as a dict
    results_list.append({
        'column': col,
        'num_predictions': scores['num_predictions'],
        'exact_match': scores['exact_match'],
        'precision': scores['precision'],
        'recall': scores['recall'],
        'f1': scores['f1'],
        'bert_score': scores['bert_similarity']
    })

# Convert list of dicts into a DataFrame
scores_df_tydiqa = pd.DataFrame(results_list)

# Optional: format the numbers to 2 decimal places
scores_df_tydiqa[['exact_match', 'precision', 'recall', 'f1', 'bert_score']] = scores_df_tydiqa[['exact_match', 'precision', 'recall', 'f1', 'bert_score']].round(4)

  0%|          | 0/514 [00:00<?, ?it/s]

100%|██████████| 514/514 [00:00<00:00, 25216.06it/s]
100%|██████████| 514/514 [00:00<00:00, 26142.24it/s]
100%|██████████| 514/514 [00:00<00:00, 26080.26it/s]
100%|██████████| 514/514 [00:00<00:00, 25670.34it/s]
100%|██████████| 514/514 [00:00<00:00, 24859.86it/s]
100%|██████████| 514/514 [00:00<00:00, 26575.02it/s]
100%|██████████| 514/514 [00:00<00:00, 26230.67it/s]
100%|██████████| 514/514 [00:00<00:00, 25605.10it/s]
100%|██████████| 514/514 [00:00<00:00, 25411.63it/s]
100%|██████████| 514/514 [00:00<00:00, 25457.25it/s]
100%|██████████| 514/514 [00:00<00:00, 25768.83it/s]
100%|██████████| 514/514 [00:00<00:00, 25778.69it/s]
100%|██████████| 514/514 [00:00<00:00, 26292.41it/s]
100%|██████████| 514/514 [00:00<00:00, 26250.15it/s]
100%|██████████| 514/514 [00:00<00:00, 26128.93it/s]
100%|██████████| 514/514 [00:00<00:00, 25864.05it/s]
100%|██████████| 514/514 [00:00<00:00, 26524.35it/s]
100%|██████████| 514/514 [00:00<00:00, 25883.31it/s]
100%|██████████| 514/514 [00:00<00:00, 25565.93it/s]
100%|██████████| 514/514 [00:00<00:00, 26208.35it/s]
100%|██████████| 514/514 [00:00<00:00, 26180.97it/s]
100%|██████████| 514/514 [00:00<00:00, 25251.80it/s]
100%|██████████| 514/514 [00:00<00:00, 24942.99it/s]
100%|██████████| 514/514 [00:00<00:00, 25670.34it/s]
100%|██████████| 514/514 [00:00<00:00, 25018.54it/s]
100%|██████████| 514/514 [00:00<00:00, 25878.64it/s]

In [16]:
pd.concat([scores_df, scores_df_tydiqa], ignore_index=True)

,column,num_predictions,exact_match,precision,recall,f1,bert_score
0,raw-idt5-base-qaqg-ae-noprefix-noprepend-42-SQ...,4980,0.0005,0.0052,0.0135,0.0059,0.2194
1,raw-idt5-base-qaqg-ae-yesprefix-noprepend-42-S...,5143,0.0005,0.0055,0.0143,0.0061,0.2199
2,raw-idt5-base-qaqg-ae-yesprefix-yesprepend-42-...,5143,0.0005,0.0055,0.0143,0.0061,0.2199
3,raw-idt5-base-qaqg-noprefix-noprepend-42-SQuAD...,4403,0.0002,0.0042,0.0109,0.0048,0.2355
4,raw-idt5-base-qaqg-qg-noprefix-noprepend-42-SQ...,1204,0.0000,0.0006,0.0013,0.0008,0.3366
5,raw-idt5-base-qaqg-qg-yesprefix-noprepend-42-S...,1204,0.0000,0.0007,0.0013,0.0008,0.3363
6,raw-idt5-base-qaqg-qg-yesprefix-yesprepend-42-...,1204,0.0000,0.0006,0.0018,0.0008,0.3348
7,raw-idt5-base-qaqg-yesprefix-noprepend-42-SQuA...,5280,0.0005,0.0055,0.0128,0.0062,0.2128
8,raw-v1-12-SQuAD-id,5243,0.0008,0.0051,0.0111,0.0056,0.2161
9,raw-v1-42-SQuAD-id,5096,0.0007,0.0046,0.0114,0.0053,0.2244
10,raw-v1-72-SQuAD-id,5202,0.0000,0.0042,0.0111,0.0048,0.2132
11,raw-v2-12-SQuAD-id,3359,0.0002,0.0023,0.0049,0.0027,0.2838
12,raw-v2-42-SQuAD-id,3796,0.0002,0.0029,0.0056,0.0032,0.2708
13,raw-v2-72-SQuAD-id,2849,0.0010,0.0034,0.0062,0.0037,0.3014
14,unique-idt5-base-qaqg-ae-noprefix-noprepend-42...,4651,0.0002,0.0039,0.0107,0.0045,0.2277
15,unique-idt5-base-qaqg-ae-yesprefix-noprepend-4...,4752,0.0002,0.0037,0.0102,0.0043,0.2297
16,unique-idt5-base-qaqg-ae-yesprefix-yesprepend-...,4752,0.0002,0.0037,0.0102,0.0043,0.2297
17,unique-idt5-base-qaqg-noprefix-noprepend-42-SQ...,4030,0.0000,0.0036,0.0100,0.0041,0.2508
18,unique-idt5-base-qaqg-qg-noprefix-noprepend-42...,1204,0.0000,0.0006,0.0013,0.0008,0.3366
19,unique-idt5-base-qaqg-qg-yesprefix-noprepend-4...,1204,0.0000,0.0007,0.0013,0.0008,0.3363
20,unique-idt5-base-qaqg-qg-yesprefix-yesprepend-...,1204,0.0000,0.0006,0.0018,0.0008,0.3348
21,unique-idt5-base-qaqg-yesprefix-noprepend-42-S...,4891,0.0002,0.0039,0.0109,0.0046,0.2273
22,unique-v1-12-SQuAD-id,4859,0.0007,0.0045,0.0113,0.0052,0.2296
23,unique-v1-42-SQuAD-id,4827,0.0000,0.0036,0.0100,0.0042,0.2315
24,unique-v1-72-SQuAD-id,4937,0.0002,0.0042,0.0116,0.0049,0.2207
25,unique-v2-12-SQuAD-id,2561,0.0000,0.0021,0.0038,0.0022,0.3072
26,unique-v2-42-SQuAD-id,2685,0.0003,0.0026,0.0048,0.0029,0.3055
27,unique-v2-72-SQuAD-id,2451,0.0008,0.0025,0.0046,0.0028,0.3116
28,raw-idt5-base-qaqg-ae-noprefix-noprepend-42-Ty...,514,0.3074,0.4303,0.4563,0.4151,0.6278
29,raw-idt5-base-qaqg-ae-yesprefix-noprepend-42-T...,514,0.3152,0.4227,0.4490,0.4061,0.6314
30,raw-idt5-base-qaqg-noprefix-noprepend-42-TydiQ...,514,0.2043,0.3141,0.3549,0.3086,0.5575
31,raw-idt5-base-qaqg-qg-noprefix-noprepend-42-Ty...,514,0.0000,0.0632,0.0898,0.0621,0.3808
32,raw-idt5-base-qaqg-qg-yesprefix-noprepend-42-T...,514,0.0000,0.0631,0.0903,0.0609,0.3740
33,raw-idt5-base-qaqg-qg-yesprefix-yesprepend-42-...,514,0.0000,0.0507,0.0586,0.0446,0.3661
34,raw-idt5-base-qaqg-yesprefix-noprepend-42-Tydi...,514,0.2899,0.4271,0.4443,0.4105,0.6327
35,raw-v1-12-TydiQA-id,514,0.3210,0.4471,0.4683,0.4313,0.6457
36,raw-v1-42-TydiQA-id,514,0.2996,0.4228,0.4421,0.4049,0.6219
37,raw-v1-72-TydiQA-id,514,0.2918,0.4297,0.4501,0.4076,0.6337
38,raw-v2-12-TydiQA-id,514,0.1907,0.3013,0.3918,0.3056,0.5433
39,raw-v2-42-TydiQA-id,514,0.2218,0.3372,0.4061,0.3369,0.5627
40,raw-v2-72-TydiQA-id,514,0.2315,0.3305,0.3524,0.3168,0.5594
41,unique-idt5-base-qaqg-ae-noprefix-noprepend-42...,514,0.3074,0.4303,0.4563,0.4151,0.6278
42,unique-idt5-base-qaqg-ae-yesprefix-noprepend-4...,514,0.3152,0.4227,0.4490,0.4061,0.6314
43,unique-idt5-base-qaqg-noprefix-noprepend-42-Ty...,514,0.2043,0.3141,0.3549,0.3086,0.5575
44,unique-idt5-base-qaqg-qg-noprefix-noprepend-42...,514,0.0000,0.0632,0.0898,0.0621,0.3808
45,unique-idt5-base-qaqg-qg-yesprefix-noprepend-4...,514,0.0000,0.0631,0.0903,0.0609,0.3740
46,unique-idt5-base-qaqg-qg-yesprefix-yesprepend-...,514,0.0000,0.0507,0.0586,0.0446,0.3661
47,unique-idt5-base-qaqg-yesprefix-noprepend-42-T...,514,0.2899,0.4271,0.4443,0.4105,0.6327
48,unique-v1-12-TydiQA-id,514,0.3210,0.4471,0.4683,0.4313,0.6457
49,unique-v1-42-TydiQA-id,514,0.2996,0.4228,0.4421,0.4049,0.6219
50,unique-v1-72-TydiQA-id,514,0.2918,0.4297,0.4501,0.4076,0.6337
51,unique-v2-12-TydiQA-id,514,0.1907,0.3013,0.3918,0.3056,0.5433
52,unique-v2-42-TydiQA-id,514,0.2218,0.3372,0.4061,0.3369,0.5627
53,unique-v2-72-TydiQA-id,514,0.2315,0.3305,0.3524,0.3168,0.5594