In [1]:
import pandas as pd

In [2]:
baseline_squad = pd.read_excel('baseline_questions.xlsx', sheet_name='squad')
baseline_tydiqa = pd.read_excel('baseline_questions.xlsx', sheet_name='tydiqa')

In [29]:
from pathlib import Path

file_squad = sorted(list(Path('.').rglob('question-generation-*-SQuAD-id.jsonl')))
file_tydiqa = sorted(list(Path('.').rglob('question-generation-*-TydiQA-id.jsonl')))

In [5]:
file_squad

[PosixPath('question-generation-v1-12-SQuAD-id.jsonl'),
 PosixPath('question-generation-v1-42-SQuAD-id.jsonl'),
 PosixPath('question-generation-v1-72-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-12-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-42-SQuAD-id.jsonl'),
 PosixPath('question-generation-v2-72-SQuAD-id.jsonl')]

In [30]:
file_tydiqa

[PosixPath('question-generation-v1-12-TydiQA-id.jsonl'),
 PosixPath('question-generation-v1-42-TydiQA-id.jsonl'),
 PosixPath('question-generation-v1-72-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-12-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-42-TydiQA-id.jsonl'),
 PosixPath('question-generation-v2-72-TydiQA-id.jsonl')]

In [ ]:
for item in file_squad:
    baseline_squad[item.name.replace('question-generation-', '')] = pd.read_json(item, lines=True)['generated_text']

In [31]:
for item in file_tydiqa:
    baseline_tydiqa[item.name.replace('question-generation-', '')] = pd.read_json(item, lines=True)['generated_text']

In [7]:
baseline_squad

,reference,baseline,v1-12-SQuAD-id.jsonl,v1-42-SQuAD-id.jsonl,v1-72-SQuAD-id.jsonl,v2-12-SQuAD-id.jsonl,v2-42-SQuAD-id.jsonl,v2-72-SQuAD-id.jsonl
0,Di negara apa Normandia berada?,Di negara mana Normandia berada?,Di negara manakah Normandia berada?,Di negara manakah Normandia berada?,Di negara manakah Normandia berada?,Di negara manakah Normandia berada?,Di negara manakah Normandia diberikan nama mer...,Di negara manakah Normandia berada?
1,Kapan Normandia di Normandia?,Apa yang terjadi dengan Normandia pada abad ke...,Pada abad berapa Normandia memberikan nama mer...,Pada abad berapa Normandia memberikan nama mer...,Pada abad berapa Bangsa Normandia memberikan n...,Pada abad berapa Normandia diberikan nama mere...,Pada abad berapa Normandia memberikan nama mer...,Kapan bangsa Normandia memberikan nama mereka ...
2,Dari negara mana asal Norse?,Apa yang terjadi dengan Normandia pada abad ke...,Dari negara manakah Normandia diturunkan?,Dari mana asal Normandia?,Dari mana asal Normandia?,Dari mana asal Normandia?,Dari mana asal Normandia?,Dari mana asal bangsa Normandia?
3,Siapa pemimpin Norse?,Siapa pemimpin Normandia?,Siapa pemimpin Normandia?,Siapa pemimpin Normandia?,Siapa pemimpin Bangsa Normandia?,"Siapa pemimpin Denmark, Islandia dan Norwegia?",Siapakah pemimpin Normandia?,Siapa yang memimpin bangsa Normandia?
4,Abad berapa pertama kali Normandia mendapatkan...,Apa yang terjadi dengan Normandia pada abad ke...,Kapan identitas budaya dan etnis yang berbeda ...,Kapan Normandia pertama kali memberikan nama m...,Kapan identitas budaya dan etnis yang berbeda ...,Kapan identitas budaya dan etnis yang berbeda ...,Kapan bangsa Normandia pertama kali memberikan...,Kapan identitas budaya dan etnis yang berbeda ...
...,...,...,...,...,...,...,...,...
5923,Apa istilah metrik yang kurang digunakan darip...,"Gaya pon memiliki padanan metrik, yang lebih j...","Gaya pon memiliki padanan metrik, yang lebih j...",Gaya pon memiliki padanan metrik apa?,Gaya apa yang diberikan oleh gravitasi standar...,Gaya pon adalah gaya yang diberikan oleh gravi...,Gaya kilopond adalah gaya yang diberikan oleh ...,Gaya apa yang diberikan oleh gravitasi standar...
5924,Seperti apa kekuatan kilogram yang kadang-kada...,Gaya kilogram kadang-kadang disebut apa?,"Gaya pon memiliki padanan metrik, yang lebih j...",Gaya kilogram kadang-kadang disebut apa?,Gaya kilogram kadang-kadang disebut apa?,Gaya kilogram kadang-kadang dikenal sebagai apa?,Apa istilah lain untuk gaya kilogram?,Apa istilah lain untuk gaya kilogram?
5925,Apakah satuan massa yang sangat jarang digunak...,Gaya apa yang paling jarang digunakan?,"Gaya pon memiliki padanan metrik, yang lebih j...",Gaya pon memiliki padanan metrik apa?,Apa massa yang berakselerasi pada 1 m · <0xC3>...,Apa massa yang berakselerasi pada 1 m · s <0xC...,Gaya metrik adalah massa yang berakselerasi pa...,Apa nama metrik untuk massa yang berakselerasi...
5926,Apa yang jarang menggunakan istilah satuan kek...,"Gaya pon memiliki padanan metrik, yang lebih j...","Gaya pon memiliki padanan metrik, yang lebih j...",Apa yang setara dengan 1000 lbf?,Unit kekuatan misterius apa yang setara dengan...,Apa unit kekuatan misterius lainnya?,Gaya kekuatan misterius apa yang setara dengan...,Unit kekuatan misterius apa yang setara dengan...
5927,Berapa satuan gaya yang jarang digunakan sama ...,Apa unit kekuatan misterius yang digunakan unt...,Unit kekuatan misterius apa yang setara dengan...,Apa unit kekuatan misterius lainnya?,Unit kekuatan misterius apa yang setara dengan...,Apa unit kekuatan misterius lainnya?,Gaya kekuatan misterius apa yang setara dengan...,Unit kekuatan misterius apa yang setara dengan...

In [32]:
baseline_tydiqa

,reference,baseline,v1-12-TydiQA-id.jsonl,v1-42-TydiQA-id.jsonl,v1-72-TydiQA-id.jsonl,v2-12-TydiQA-id.jsonl,v2-42-TydiQA-id.jsonl,v2-72-TydiQA-id.jsonl
0,Siapakah yang menemuka benua Amerika ?,Kapan Kolumbus lahir?,Kapan Kolumbus masuk ke benua Amerika ?,Berapa lama Kolumbus masuk ke benua Amerika?,Kapan John Columbus lahir ?,Berapa lama Columbus masuk ke benua Amerika?,Kapan Columbus pertama kali masuk ke benua Ame...,Kapan John Columbus masuk ke benua Amerika ?
1,Dimanakah letak Donggala ?,"4275,08km2",Berapa luas Kabupaten Donggala?,berapakah luas Kabupaten Donggala?,berapakah luas Kabupaten Donggala?,berapakah luas Kabupaten Donggala?,berapakah luas Kabupaten Donggala?,Apakah luas Kabupaten Donggala?
2,Siapa bapak Teknik industri?,Kapan Teknik Industri muncul?,Siapa yang menemukan ilmu Ekonomi ?,Ada berapa tahun Adam Smith menciptakan ilmu E...,Siapa yang menemukan ilmu Economic Science?,Siapa yang menemukan ilmu Economic Science?,Siapa yang menemukan ilmu Economic Science?,Siapa yang menemukan ilmu Ekonomi ?
3,Kapan Penghulu Rasyid meninggal ?,Kapan Penghulu Rasyid meninggal?,Kapan Penghulu Rasyid lahir?,Berapa umur Penghulu Rasyid?,Kapan Penghulu Rasyid lahir?,Kapan Penghulu Rasyid lahir?,Kapan Penghulu Rasyid lahir?,Kapan Penghulu Rasyid lahir?
4,seberapa luas kah samudera pasifik?,Berapa luas Samudra Pasifik?,Berapa luas Samudra Pasifik?,"179,7 juta km2",Berapa luas Samudra Pasifik?,Berapa luas Samudra Pasifik?,Berapa luas Samudra Pasifik?,berapakah luas Samudra Pasifik?
...,...,...,...,...,...,...,...,...
560,Dimana kantor pusat PT Scooter Victory Inter P...,Kapan PT Scooter Victory Inter Part didirikan?,Siapa pendiri PT Scooter Victory Inter Part?,Apakah kode telepon PT Scooter Victory Inter P...,Apakah nama kantor pusat Scooter Victory Inter...,Apakah kode perusahaan Scooter Victory Inter P...,Apakah kode perusahaan Scooter Victory Inter P...,Siapa pendiri Scooter Victory Inter Part?
561,Kapan Teori hubungan internasional diciptakan?,E. H. Carr,Kapan ilmu hubungan internasional ditemukan ?,Apakah jumlah buku The Twenty Years' Crisis?,Kapan ilmu hubungan internasional ditemukan ?,Kapan ilmu hubungan internasional ditemukan ?,Kapan ilmu hubungan internasional ditemukan ?,Kapan ilmu hubungan internasional ditemukan ?
562,kapan musik hip hop pertama kali muncul ?,Kapan musik hip hop pertama kali diciptakan?,apakah yang dimaksud dengan musik hip hop?,Apakah unsur kunci dalam musik hip hop?,Ada berapa genre musik hip hop?,Ada berapa jenis musik yang digunakan dalam mu...,Ada berapa unsur dalam musik Hip hop?,Apakah unsur utama dari musik hip-hop?
563,Berapa luas SMK Negeri 1 Cikampek?,28997m2,berapakah jumlah kampus di SMK Negeri 1 Cikampek?,Berapa jumlah kampus di SMK Negeri 1 Cikampek?,Berapa jumlah kampus di SMK Negeri 1 Cikampek?,Berapa jumlah kampus di SMK Negeri 1 Cikampek?,Berapa jumlah kampus di SMK Negeri 1 Cikampek?,Berapa jumlah kampus di SMK Negeri 1 Cikampek?
564,Berapakah berat Ikan pari manta yag terbesar?,Siapakah yang menemukan ikan pari manta?,berapakah berat Ikan pari manta?,Berapa Bobot terberat Ikan pari manta?,Berapa berat ikan pari manta?,Berapa berat Ikan pari manta?,Berapa Bobot Ikan Pari manta?,Berapa berat ikan Pari manta?

In [21]:
import evaluate
from sentence_transformers import SentenceTransformer
from tqdm import tqdm

bleu = evaluate.load("bleu")
rouge = evaluate.load('rouge')

model = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

def compute_score(generated_list_of_content, reference):
    bleu_score = bleu.compute(predictions=generated_list_of_content, references=reference)
    precision_keys = ['bleu1', 'bleu2', 'bleu3', 'bleu4']
    for i, key in enumerate(precision_keys):
        bleu_score[key] = bleu_score['precisions'][i]    
    del bleu_score['precisions']
    rouge_score = rouge.compute(predictions=generated_list_of_content, references=reference)

    bert_scores = [model.similarity(model.encode(each), model.encode(reference[i]))[0] 
                                    for i, each in 
                                        enumerate(generated_list_of_content)
                                        ]
    average_bert_scores = {"bert_score": sum(bert_scores)/len(bert_scores)}

    return {**bleu_score, 
            **{k: float(v) for k, v in rouge_score.items()}, 
            **{k: float(v) for k, v in average_bert_scores.items()}}

'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c4f0d2a1-87df-4e90-aaa3-5fce63727ffd)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/./modules.json
WARNING:huggingface_hub.utils._http:'(ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=10)"), '(Request ID: c4f0d2a1-87df-4e90-aaa3-5fce63727ffd)')' thrown while requesting HEAD https://huggingface.co/sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2/resolve/main/./modules.json
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

In [24]:
all_scores = []
for col in baseline_squad.columns[1:]:
    temp_scores = []
    for i, item in enumerate(tqdm(baseline_squad['reference'])):
        scores = compute_score([baseline_squad.loc[i, col]], [item])
        temp_scores.append(scores)
    all_scores.append({'column': col, 'scores': temp_scores})

100%|██████████| 5928/5928 [04:49<00:00, 20.46it/s]
100%|██████████| 5928/5928 [04:45<00:00, 20.74it/s]
100%|██████████| 5928/5928 [04:48<00:00, 20.54it/s]
100%|██████████| 5928/5928 [04:49<00:00, 20.46it/s]
100%|██████████| 5928/5928 [04:50<00:00, 20.42it/s]
100%|██████████| 5928/5928 [04:49<00:00, 20.46it/s]
100%|██████████| 5928/5928 [04:49<00:00, 20.50it/s]

In [25]:
all_scores

[{'column': 'baseline',
  'scores': [{'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 6,
    'reference_length': 6,
    'bleu1': 0.8333333333333334,
    'bleu2': 0.6,
    'bleu3': 0.25,
    'bleu4': 0.0,
    'rouge1': 0.8000000000000002,
    'rouge2': 0.5,
    'rougeL': 0.8000000000000002,
    'rougeLsum': 0.8000000000000002,
    'bert_score': 0.9915947914123535},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.2,
    'translation_length': 11,
    'reference_length': 5,
    'bleu1': 0.18181818181818182,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.125,
    'rouge2': 0.0,
    'rougeL': 0.125,
    'rougeLsum': 0.125,
    'bert_score': 0.8074707388877869},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.8333333333333333,
    'translation_length': 11,
    'reference_length': 6,
    'bleu1': 0.09090909090909091,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.39268940687179565},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 4,
    'reference_length': 4,
    'bleu1': 0.75,
    'bleu2': 0.3333333333333333,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.6666666666666666,
    'rouge2': 0.5,
    'rougeL': 0.6666666666666666,
    'rougeLsum': 0.6666666666666666,
    'bert_score': 0.5640232563018799},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 11,
    'reference_length': 11,
    'bleu1': 0.2727272727272727,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.2727272727272727,
    'rouge2': 0.0,
    'rougeL': 0.0909090909090909,
    'rougeLsum': 0.0909090909090909,
    'bert_score': 0.7602887749671936},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.474570631980896},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.6,
    'translation_length': 13,
    'reference_length': 5,
    'bleu1': 0.15384615384615385,
    'bleu2': 0.08333333333333333,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.23529411764705882,
    'rouge2': 0.13333333333333333,
    'rougeL': 0.23529411764705882,
    'rougeLsum': 0.23529411764705882,
    'bert_score': 0.5082954168319702},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.75,
    'translation_length': 7,
    'reference_length': 4,
    'bleu1': 0.14285714285714285,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4,
    'rouge2': 0.0,
    'rougeL': 0.2,
    'rougeLsum': 0.2,
    'bert_score': 0.7906472086906433},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.42857142857142855,
    'bleu2': 0.16666666666666666,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3333333333333333,
    'rouge2': 0.20000000000000004,
    'rougeL': 0.3333333333333333,
    'rougeLsum': 0.3333333333333333,
    'bert_score': 0.40415284037590027},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.2222222222222223,
    'translation_length': 11,
    'reference_length': 9,
    'bleu1': 0.09090909090909091,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.48828473687171936},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 0.8,
    'bleu2': 0.5,
    'bleu3': 0.3333333333333333,
    'bleu4': 0.0,
    'rouge1': 0.75,
    'rouge2': 0.6666666666666666,
    'rougeL': 0.75,
    'rougeLsum': 0.75,
    'bert_score': 0.903544008731842},
   {'bleu': 0.0,
    'brevity_penalty': 0.846481724890614,
    'length_ratio': 0.8571428571428571,
    'translation_length': 6,
    'reference_length': 7,
    'bleu1': 0.16666666666666666,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.14285714285714285,
    'rouge2': 0.0,
    'rougeL': 0.14285714285714285,
    'rougeLsum': 0.14285714285714285,
    'bert_score': 0.5368502140045166},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.6666666666666667,
    'translation_length': 10,
    'reference_length': 6,
    'bleu1': 0.1,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.14285714285714285,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.3644120693206787},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 10,
    'reference_length': 12,
    'bleu1': 0.2,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.09523809523809525,
    'rouge2': 0.0,
    'rougeL': 0.09523809523809525,
    'rougeLsum': 0.09523809523809525,
    'bert_score': 0.26714932918548584},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.75,
    'translation_length': 11,
    'reference_length': 4,
    'bleu1': 0.2727272727272727,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.30769230769230765,
    'rouge2': 0.0,
    'rougeL': 0.30769230769230765,
    'rougeLsum': 0.30769230769230765,
    'bert_score': 0.5781902074813843},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 6,
    'reference_length': 9,
    'bleu1': 0.3333333333333333,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3076923076923077,
    'rouge2': 0.0,
    'rougeL': 0.15384615384615385,
    'rougeLsum': 0.15384615384615385,
    'bert_score': 0.374541312456131},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 3.142857142857143,
    'translation_length': 22,
    'reference_length': 7,
    'bleu1': 0.09090909090909091,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.13793103448275862,
    'rouge2': 0.0,
    'rougeL': 0.13793103448275862,
    'rougeLsum': 0.13793103448275862,
    'bert_score': 0.37928128242492676},
   {'bleu': 0.0,
    'brevity_penalty': 0.7165313105737893,
    'length_ratio': 0.75,
    'translation_length': 9,
    'reference_length': 12,
    'bleu1': 0.2222222222222222,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.11111111111111112,
    'rouge2': 0.0,
    'rougeL': 0.11111111111111112,
    'rougeLsum': 0.11111111111111112,
    'bert_score': 0.6776925325393677},
   {'bleu': 0.6434588841607617,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.8571428571428571,
    'bleu2': 0.6666666666666666,
    'bleu3': 0.6,
    'bleu4': 0.5,
    'rouge1': 0.8333333333333334,
    'rouge2': 0.6,
    'rougeL': 0.8333333333333334,
    'rougeLsum': 0.8333333333333334,
    'bert_score': 0.986339807510376},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.8333333333333333,
    'translation_length': 11,
    'reference_length': 6,
    'bleu1': 0.5454545454545454,
    'bleu2': 0.3,
    'bleu3': 0.1111111111111111,
    'bleu4': 0.0,
    'rouge1': 0.625,
    'rouge2': 0.28571428571428575,
    'rougeL': 0.625,
    'rougeLsum': 0.625,
    'bert_score': 0.8297522068023682},
   {'bleu': 0.0,
    'brevity_penalty': 0.5647181220077593,
    'length_ratio': 0.6363636363636364,
    'translation_length': 7,
    'reference_length': 11,
    'bleu1': 0.8571428571428571,
    'bleu2': 0.5,
    'bleu3': 0.2,
    'bleu4': 0.0,
    'rouge1': 0.625,
    'rouge2': 0.42857142857142855,
    'rougeL': 0.625,
    'rougeLsum': 0.625,
    'bert_score': 0.7921711206436157},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.2,
    'translation_length': 11,
    'reference_length': 5,
    'bleu1': 0.18181818181818182,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4285714285714285,
    'rouge2': 0.0,
    'rougeL': 0.28571428571428575,
    'rougeLsum': 0.28571428571428575,
    'bert_score': 0.5147885680198669},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.6666666666666667,
    'translation_length': 15,
    'reference_length': 9,
    'bleu1': 0.26666666666666666,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3,
    'rouge2': 0.0,
    'rougeL': 0.3,
    'rougeLsum': 0.3,
    'bert_score': 0.6331424713134766},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.75,
    'translation_length': 14,
    'reference_length': 8,
    'bleu1': 0.2857142857142857,
    'bleu2': 0.07692307692307693,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4,
    'rouge2': 0.0,
    'rougeL': 0.4,
    'rougeLsum': 0.4,
    'bert_score': 0.8503792881965637},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 3.3333333333333335,
    'translation_length': 20,
    'reference_length': 6,
    'bleu1': 0.1,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.08333333333333333,
    'rouge2': 0.0,
    'rougeL': 0.08333333333333333,
    'rougeLsum': 0.08333333333333333,
    'bert_score': 0.5131783485412598},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.5,
    'translation_length': 10,
    'reference_length': 4,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.3318077325820923},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.3333333333333333,
    'translation_length': 8,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.16666666666666666,
    'rouge2': 0.0,
    'rougeL': 0.16666666666666666,
    'rougeLsum': 0.16666666666666666,
    'bert_score': 0.43696749210357666},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.4285714285714286,
    'translation_length': 10,
    'reference_length': 7,
    'bleu1': 0.5,
    'bleu2': 0.1111111111111111,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5333333333333333,
    'rouge2': 0.15384615384615385,
    'rougeL': 0.5333333333333333,
    'rougeLsum': 0.5333333333333333,
    'bert_score': 0.6204923391342163},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 6,
    'reference_length': 9,
    'bleu1': 0.5,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3076923076923077,
    'rouge2': 0.18181818181818182,
    'rougeL': 0.3076923076923077,
    'rougeLsum': 0.3076923076923077,
    'bert_score': 0.3426143527030945},
   {'bleu': 1.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 4,
    'reference_length': 4,
    'bleu1': 1.0,
    'bleu2': 1.0,
    'bleu3': 1.0,
    'bleu4': 1.0,
    'rouge1': 1.0,
    'rouge2': 1.0,
    'rougeL': 1.0,
    'rougeLsum': 1.0,
    'bert_score': 1.0},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 6,
    'reference_length': 6,
    'bleu1': 0.16666666666666666,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.3856484889984131},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.4622570872306824},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.2857142857142858,
    'translation_length': 9,
    'reference_length': 7,
    'bleu1': 0.5555555555555556,
    'bleu2': 0.25,
    'bleu3': 0.14285714285714285,
    'bleu4': 0.0,
    'rouge1': 0.5714285714285715,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5714285714285715,
    'rougeLsum': 0.5714285714285715,
    'bert_score': 0.5768518447875977},
   {'bleu': 1.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 1.0,
    'bleu2': 1.0,
    'bleu3': 1.0,
    'bleu4': 1.0,
    'rouge1': 1.0,
    'rouge2': 1.0,
    'rougeL': 1.0,
    'rougeLsum': 1.0,
    'bert_score': 1.000000238418579},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.5,
    'translation_length': 9,
    'reference_length': 6,
    'bleu1': 0.3333333333333333,
    'bleu2': 0.125,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3076923076923077,
    'rouge2': 0.18181818181818182,
    'rougeL': 0.3076923076923077,
    'rougeLsum': 0.3076923076923077,
    'bert_score': 0.1909385621547699},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.75,
    'translation_length': 11,
    'reference_length': 4,
    'bleu1': 0.09090909090909091,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.20455440878868103},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.3333333333333333,
    'translation_length': 8,
    'reference_length': 6,
    'bleu1': 0.125,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2290404736995697},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.0,
    'translation_length': 10,
    'reference_length': 5,
    'bleu1': 0.4,
    'bleu2': 0.1111111111111111,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.46153846153846156,
    'rouge2': 0.18181818181818182,
    'rougeL': 0.46153846153846156,
    'rougeLsum': 0.46153846153846156,
    'bert_score': 0.8022259473800659},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.1428571428571428,
    'translation_length': 8,
    'reference_length': 7,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.15384615384615383,
    'rouge2': 0.0,
    'rougeL': 0.15384615384615383,
    'rougeLsum': 0.15384615384615383,
    'bert_score': 0.4523516893386841},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.5,
    'translation_length': 10,
    'reference_length': 4,
    'bleu1': 0.4,
    'bleu2': 0.1111111111111111,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5,
    'rouge2': 0.2,
    'rougeL': 0.5,
    'rougeLsum': 0.5,
    'bert_score': 0.8282537460327148},
   {'bleu': 0.36889397323344053,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 9,
    'reference_length': 9,
    'bleu1': 0.7777777777777778,
    'bleu2': 0.5,
    'bleu3': 0.2857142857142857,
    'bleu4': 0.16666666666666666,
    'rouge1': 0.75,
    'rouge2': 0.42857142857142855,
    'rougeL': 0.75,
    'rougeLsum': 0.75,
    'bert_score': 0.9648038744926453},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.6666666666666667,
    'translation_length': 10,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.2222222222222222,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5714285714285714,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5714285714285714,
    'rougeLsum': 0.5714285714285714,
    'bert_score': 0.8426656723022461},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.1666666666666667,
    'translation_length': 7,
    'reference_length': 6,
    'bleu1': 0.42857142857142855,
    'bleu2': 0.16666666666666666,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3636363636363636,
    'rouge2': 0.22222222222222224,
    'rougeL': 0.3636363636363636,
    'rougeLsum': 0.3636363636363636,
    'bert_score': 0.41334038972854614},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.25,
    'translation_length': 9,
    'reference_length': 4,
    'bleu1': 0.2222222222222222,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.18181818181818182,
    'rouge2': 0.0,
    'rougeL': 0.18181818181818182,
    'rougeLsum': 0.18181818181818182,
    'bert_score': 0.524726152420044},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 9,
    'reference_length': 9,
    'bleu1': 0.4444444444444444,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.35294117647058826,
    'rouge2': 0.0,
    'rougeL': 0.35294117647058826,
    'rougeLsum': 0.35294117647058826,
    'bert_score': 0.7519341707229614},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.8333333333333333,
    'translation_length': 11,
    'reference_length': 6,
    'bleu1': 0.36363636363636365,
    'bleu2': 0.1,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4705882352941177,
    'rouge2': 0.26666666666666666,
    'rougeL': 0.4705882352941177,
    'rougeLsum': 0.4705882352941177,
    'bert_score': 0.735360860824585},
   {'bleu': 0.3266828640925502,
    'brevity_penalty': 0.751477293075286,
    'length_ratio': 0.7777777777777778,
    'translation_length': 7,
    'reference_length': 9,
    'bleu1': 0.7142857142857143,
    'bleu2': 0.5,
    'bleu3': 0.4,
    'bleu4': 0.25,
    'rouge1': 0.5714285714285715,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5714285714285715,
    'rougeLsum': 0.5714285714285715,
    'bert_score': 0.8223886489868164},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.375,
    'translation_length': 11,
    'reference_length': 8,
    'bleu1': 0.36363636363636365,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3529411764705882,
    'rouge2': 0.0,
    'rougeL': 0.23529411764705882,
    'rougeLsum': 0.23529411764705882,
    'bert_score': 0.6995143890380859},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 2.0,
    'translation_length': 18,
    'reference_length': 9,
    'bleu1': 0.2222222222222222,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.31999999999999995,
    'rouge2': 0.0,
    'rougeL': 0.15999999999999998,
    'rougeLsum': 0.15999999999999998,
    'bert_score': 0.8477193117141724},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.4,
    'translation_length': 7,
    'reference_length': 5,
    'bleu1': 0.2857142857142857,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.1818181818181818,
    'rouge2': 0.0,
    'rougeL': 0.1818181818181818,
    'rougeLsum': 0.1818181818181818,
    'bert_score': 0.3178119957447052},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.25,
    'translation_length': 5,
    'reference_length': 4,
    'bleu1': 0.6,
    'bleu2': 0.25,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5714285714285715,
    'rouge2': 0.0,
    'rougeL': 0.5714285714285715,
    'rougeLsum': 0.5714285714285715,
    'bert_score': 0.9332402348518372},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.8,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.6666666666666665,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.9378310441970825},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.5,
    'translation_length': 6,
    'reference_length': 4,
    'bleu1': 0.3333333333333333,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.3614546060562134},
   {'bleu': 0.3655552228545123,
    'brevity_penalty': 1.0,
    'length_ratio': 1.3333333333333333,
    'translation_length': 8,

In [26]:
with open('temporary-squad-scores.json', 'w') as f:
    import json
    json.dump(all_scores, f, indent=4)

In [33]:
all_scores_tydiqa = []
for col in baseline_tydiqa.columns[1:]:
    temp_scores = []
    for i, item in enumerate(tqdm(baseline_tydiqa['reference'])):
        scores = compute_score([baseline_tydiqa.loc[i, col]], [item])
        temp_scores.append(scores)
    all_scores_tydiqa.append({'column': col, 'scores': temp_scores})

100%|██████████| 565/565 [00:27<00:00, 20.88it/s]
100%|██████████| 565/565 [00:27<00:00, 20.63it/s]
100%|██████████| 565/565 [00:27<00:00, 20.64it/s]
100%|██████████| 565/565 [00:27<00:00, 20.65it/s]
100%|██████████| 565/565 [00:27<00:00, 20.46it/s]
100%|██████████| 565/565 [00:27<00:00, 20.41it/s]
100%|██████████| 565/565 [00:27<00:00, 20.53it/s]

In [34]:
all_scores_tydiqa

[{'column': 'baseline',
  'scores': [{'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2498466521501541},
   {'bleu': 0.0,
    'brevity_penalty': 0.049787068367863944,
    'length_ratio': 0.25,
    'translation_length': 1,
    'reference_length': 4,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2609027326107025},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5,
    'rougeLsum': 0.5,
    'bert_score': 0.6782943606376648},
   {'bleu': 1.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 1.0,
    'bleu2': 1.0,
    'bleu3': 1.0,
    'bleu4': 1.0,
    'rouge1': 1.0,
    'rouge2': 1.0,
    'rougeL': 1.0,
    'rougeLsum': 1.0,
    'bert_score': 0.9984414577484131},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.9654137492179871},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.6798677444458008},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.8571428571428572,
    'translation_length': 13,
    'reference_length': 7,
    'bleu1': 0.23076923076923078,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.2222222222222222,
    'rouge2': 0.0,
    'rougeL': 0.2222222222222222,
    'rougeLsum': 0.2222222222222222,
    'bert_score': 0.7483092546463013},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 6,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4000000000000001,
    'rouge2': 0.25,
    'rougeL': 0.4000000000000001,
    'rougeLsum': 0.4000000000000001,
    'bert_score': 0.749508261680603},
   {'bleu': 0.0,
    'brevity_penalty': 0.22313016014842982,
    'length_ratio': 0.4,
    'translation_length': 2,
    'reference_length': 5,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.49882301688194275},
   {'bleu': 0.0,
    'brevity_penalty': 0.6703200460356393,
    'length_ratio': 0.7142857142857143,
    'translation_length': 5,
    'reference_length': 7,
    'bleu1': 0.2,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.41000688076019287},
   {'bleu': 0.0,
    'brevity_penalty': 0.36787944117144233,
    'length_ratio': 0.5,
    'translation_length': 5,
    'reference_length': 10,
    'bleu1': 0.2,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.24887941777706146},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.3333333333333333,
    'translation_length': 8,
    'reference_length': 6,
    'bleu1': 0.625,
    'bleu2': 0.2857142857142857,
    'bleu3': 0.16666666666666666,
    'bleu4': 0.0,
    'rouge1': 0.6666666666666666,
    'rouge2': 0.4,
    'rougeL': 0.6666666666666666,
    'rougeLsum': 0.6666666666666666,
    'bert_score': 0.6324533224105835},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.7478009462356567},
   {'bleu': 0.7598356856515925,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 6,
    'reference_length': 6,
    'bleu1': 0.8333333333333334,
    'bleu2': 0.8,
    'bleu3': 0.75,
    'bleu4': 0.6666666666666666,
    'rouge1': 0.8000000000000002,
    'rouge2': 0.75,
    'rougeL': 0.8000000000000002,
    'rougeLsum': 0.8000000000000002,
    'bert_score': 0.9965671896934509},
   {'bleu': 0.48882903186579435,
    'brevity_penalty': 0.8007374029168082,
    'length_ratio': 0.8181818181818182,
    'translation_length': 9,
    'reference_length': 11,
    'bleu1': 0.7777777777777778,
    'bleu2': 0.625,
    'bleu3': 0.5714285714285714,
    'bleu4': 0.5,
    'rouge1': 0.6666666666666665,
    'rouge2': 0.6250000000000001,
    'rougeL': 0.6666666666666665,
    'rougeLsum': 0.6666666666666665,
    'bert_score': 0.8508878946304321},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.14285714285714285,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.43982023000717163},
   {'bleu': 0.0,
    'brevity_penalty': 0.01831563888873418,
    'length_ratio': 0.2,
    'translation_length': 1,
    'reference_length': 5,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2768290638923645},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.4,
    'translation_length': 7,
    'reference_length': 5,
    'bleu1': 0.42857142857142855,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.22222222222222224,
    'rougeLsum': 0.22222222222222224,
    'bert_score': 0.6337789297103882},
   {'bleu': 0.0,
    'brevity_penalty': 0.4723665527410147,
    'length_ratio': 0.5714285714285714,
    'translation_length': 4,
    'reference_length': 7,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.4133737087249756},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2632245123386383},
   {'bleu': 0.0,
    'brevity_penalty': 0.1353352832366127,
    'length_ratio': 0.3333333333333333,
    'translation_length': 2,
    'reference_length': 6,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.1027175635099411},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.28571428571428575,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.8307422399520874},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 5,
    'reference_length': 5,
    'bleu1': 0.6,
    'bleu2': 0.25,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5,
    'rougeLsum': 0.5,
    'bert_score': 0.5089678168296814},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.36254751682281494},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.2,
    'translation_length': 6,
    'reference_length': 5,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.8977397680282593},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.14285714285714285,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.16666666666666666,
    'rouge2': 0.0,
    'rougeL': 0.16666666666666666,
    'rougeLsum': 0.16666666666666666,
    'bert_score': 0.42512065172195435},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.2,
    'translation_length': 6,
    'reference_length': 5,
    'bleu1': 0.5,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.5775972604751587},
   {'bleu': 0.4329820146406897,
    'brevity_penalty': 0.7165313105737893,
    'length_ratio': 0.75,
    'translation_length': 6,
    'reference_length': 8,
    'bleu1': 1.0,
    'bleu2': 0.8,
    'bleu3': 0.5,
    'bleu4': 0.3333333333333333,
    'rouge1': 0.8571428571428571,
    'rouge2': 0.6666666666666666,
    'rougeL': 0.8571428571428571,
    'rougeLsum': 0.8571428571428571,
    'bert_score': 0.9442985653877258},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5,
    'rouge2': 0.3333333333333333,
    'rougeL': 0.5,
    'rougeLsum': 0.5,
    'bert_score': 0.8551820516586304},
   {'bleu': 0.0,
    'brevity_penalty': 0.36787944117144233,
    'length_ratio': 0.5,
    'translation_length': 3,
    'reference_length': 6,
    'bleu1': 1.0,
    'bleu2': 1.0,
    'bleu3': 1.0,
    'bleu4': 0.0,
    'rouge1': 0.7499999999999999,
    'rouge2': 0.6666666666666666,
    'rougeL': 0.7499999999999999,
    'rougeLsum': 0.7499999999999999,
    'bert_score': 0.8410708904266357},
   {'bleu': 0.0,
    'brevity_penalty': 0.846481724890614,
    'length_ratio': 0.8571428571428571,
    'translation_length': 6,
    'reference_length': 7,
    'bleu1': 0.6666666666666666,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5454545454545454,
    'rouge2': 0.22222222222222224,
    'rougeL': 0.5454545454545454,
    'rougeLsum': 0.5454545454545454,
    'bert_score': 0.7650494575500488},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.8496761322021484},
   {'bleu': 0.0,
    'brevity_penalty': 0.006737946999085467,
    'length_ratio': 0.16666666666666666,
    'translation_length': 1,
    'reference_length': 6,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.3558764159679413},
   {'bleu': 0.0,
    'brevity_penalty': 0.846481724890614,
    'length_ratio': 0.8571428571428571,
    'translation_length': 6,
    'reference_length': 7,
    'bleu1': 0.5,
    'bleu2': 0.4,
    'bleu3': 0.25,
    'bleu4': 0.0,
    'rouge1': 0.3636363636363636,
    'rouge2': 0.22222222222222224,
    'rougeL': 0.3636363636363636,
    'rougeLsum': 0.3636363636363636,
    'bert_score': 0.7808018922805786},
   {'bleu': 0.0,
    'brevity_penalty': 0.751477293075286,
    'length_ratio': 0.7777777777777778,
    'translation_length': 7,
    'reference_length': 9,
    'bleu1': 0.2857142857142857,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.13333333333333333,
    'rouge2': 0.0,
    'rougeL': 0.13333333333333333,
    'rougeLsum': 0.13333333333333333,
    'bert_score': 0.6194676756858826},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.4,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.28571428571428575,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.8167376518249512},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 6,
    'reference_length': 9,
    'bleu1': 0.5,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3076923076923077,
    'rouge2': 0.18181818181818182,
    'rougeL': 0.3076923076923077,
    'rougeLsum': 0.3076923076923077,
    'bert_score': 0.6926454305648804},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.6,
    'translation_length': 8,
    'reference_length': 5,
    'bleu1': 0.125,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.18181818181818182,
    'rouge2': 0.0,
    'rougeL': 0.18181818181818182,
    'rougeLsum': 0.18181818181818182,
    'bert_score': 0.5864347219467163},
   {'bleu': 0.0,
    'brevity_penalty': 0.6065306597126334,
    'length_ratio': 0.6666666666666666,
    'translation_length': 4,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.25,
    'rouge2': 0.0,
    'rougeL': 0.25,
    'rougeLsum': 0.25,
    'bert_score': 0.42278850078582764},
   {'bleu': 0.0,
    'brevity_penalty': 0.513417119032592,
    'length_ratio': 0.6,
    'translation_length': 6,
    'reference_length': 10,
    'bleu1': 0.5,
    'bleu2': 0.2,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.2857142857142857,
    'rouge2': 0.16666666666666666,
    'rougeL': 0.2857142857142857,
    'rougeLsum': 0.2857142857142857,
    'bert_score': 0.6899121403694153},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 4,
    'reference_length': 4,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3333333333333333,
    'rouge2': 0.0,
    'rougeL': 0.3333333333333333,
    'rougeLsum': 0.3333333333333333,
    'bert_score': 0.7849905490875244},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.1666666666666667,
    'translation_length': 7,
    'reference_length': 6,
    'bleu1': 0.14285714285714285,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.14666734635829926},
   {'bleu': 0.0,
    'brevity_penalty': 0.006737946999085467,
    'length_ratio': 0.16666666666666666,
    'translation_length': 1,
    'reference_length': 6,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.12885427474975586},
   {'bleu': 0.0,
    'brevity_penalty': 0.2635971381157267,
    'length_ratio': 0.42857142857142855,
    'translation_length': 3,
    'reference_length': 7,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.3147769868373871},
   {'bleu': 0.0,
    'brevity_penalty': 0.36787944117144233,
    'length_ratio': 0.5,
    'translation_length': 4,
    'reference_length': 8,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4,
    'rouge2': 0.25,
    'rougeL': 0.4,
    'rougeLsum': 0.4,
    'bert_score': 0.8161954879760742},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.6,
    'bleu2': 0.25,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.6666666666666665,
    'rouge2': 0.5714285714285715,
    'rougeL': 0.6666666666666665,
    'rougeLsum': 0.6666666666666665,
    'bert_score': 0.9201012849807739},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 4,
    'reference_length': 4,
    'bleu1': 0.5,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.3333333333333333,
    'rouge2': 0.0,
    'rougeL': 0.3333333333333333,
    'rougeLsum': 0.3333333333333333,
    'bert_score': 0.8809524774551392},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.3333333333333333,
    'translation_length': 8,
    'reference_length': 6,
    'bleu1': 0.25,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.5,
    'rouge2': 0.0,
    'rougeL': 0.5,
    'rougeLsum': 0.5,
    'bert_score': 0.9597964286804199},
   {'bleu': 0.0,
    'brevity_penalty': 0.0009118819655545162,
    'length_ratio': 0.125,
    'translation_length': 1,
    'reference_length': 8,
    'bleu1': 0.0,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.2547391951084137},
   {'bleu': 0.0,
    'brevity_penalty': 0.8187307530779819,
    'length_ratio': 0.8333333333333334,
    'translation_length': 5,
    'reference_length': 6,
    'bleu1': 0.6,
    'bleu2': 0.25,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.4444444444444445,
    'rouge2': 0.0,
    'rougeL': 0.4444444444444445,
    'rougeLsum': 0.4444444444444445,
    'bert_score': 0.8491687774658203},
   {'bleu': 0.6434588841607617,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.8571428571428571,
    'bleu2': 0.6666666666666666,
    'bleu3': 0.6,
    'bleu4': 0.5,
    'rouge1': 0.8333333333333334,
    'rouge2': 0.8000000000000002,
    'rougeL': 0.8333333333333334,
    'rougeLsum': 0.8333333333333334,
    'bert_score': 0.9860109090805054},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 7,
    'reference_length': 7,
    'bleu1': 0.14285714285714285,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.0,
    'rouge2': 0.0,
    'rougeL': 0.0,
    'rougeLsum': 0.0,
    'bert_score': 0.6660315990447998},
   {'bleu': 0.0,
    'brevity_penalty': 0.7788007830714049,
    'length_ratio': 0.8,
    'translation_length': 4,
    'reference_length': 5,
    'bleu1': 1.0,
    'bleu2': 0.6666666666666666,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.888888888888889,
    'rouge2': 0.5714285714285715,
    'rougeL': 0.888888888888889,
    'rougeLsum': 0.888888888888889,
    'bert_score': 0.9196037650108337},
   {'bleu': 0.0,
    'brevity_penalty': 1.0,
    'length_ratio': 1.0,
    'translation_length': 6,
    'reference_length': 6,
    'bleu1': 0.3333333333333333,
    'bleu2': 0.0,
    'bleu3': 0.0,
    'bleu4': 0.0,
    'rouge1': 0.20000000000000004,
    'rouge2': 0.0,
    'rougeL': 0.20000000000000004,
    'rougeLsum': 0.20000000000000004,
    'bert_score': 0.7377526760101318},
   {'bleu': 0.0,
    'brevity_penalty': 0.36787944117144233,
    'length_ratio': 0.5,

In [35]:
with open('temporary-tydiqa-scores.json', 'w') as f:
    import json
    json.dump(all_scores_tydiqa, f, indent=4)

In [38]:
all_scores[0]['scores']

[{'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 6,
  'reference_length': 6,
  'bleu1': 0.8333333333333334,
  'bleu2': 0.6,
  'bleu3': 0.25,
  'bleu4': 0.0,
  'rouge1': 0.8000000000000002,
  'rouge2': 0.5,
  'rougeL': 0.8000000000000002,
  'rougeLsum': 0.8000000000000002,
  'bert_score': 0.9915947914123535},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.2,
  'translation_length': 11,
  'reference_length': 5,
  'bleu1': 0.18181818181818182,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.125,
  'rouge2': 0.0,
  'rougeL': 0.125,
  'rougeLsum': 0.125,
  'bert_score': 0.8074707388877869},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.8333333333333333,
  'translation_length': 11,
  'reference_length': 6,
  'bleu1': 0.09090909090909091,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.39268940687179565},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 4,
  'reference_length': 4,
  'bleu1': 0.75,
  'bleu2': 0.3333333333333333,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.6666666666666666,
  'rouge2': 0.5,
  'rougeL': 0.6666666666666666,
  'rougeLsum': 0.6666666666666666,
  'bert_score': 0.5640232563018799},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 11,
  'reference_length': 11,
  'bleu1': 0.2727272727272727,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.2727272727272727,
  'rouge2': 0.0,
  'rougeL': 0.0909090909090909,
  'rougeLsum': 0.0909090909090909,
  'bert_score': 0.7602887749671936},
 {'bleu': 0.0,
  'brevity_penalty': 0.6065306597126334,
  'length_ratio': 0.6666666666666666,
  'translation_length': 4,
  'reference_length': 6,
  'bleu1': 0.5,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.25,
  'rouge2': 0.0,
  'rougeL': 0.25,
  'rougeLsum': 0.25,
  'bert_score': 0.474570631980896},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.6,
  'translation_length': 13,
  'reference_length': 5,
  'bleu1': 0.15384615384615385,
  'bleu2': 0.08333333333333333,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.23529411764705882,
  'rouge2': 0.13333333333333333,
  'rougeL': 0.23529411764705882,
  'rougeLsum': 0.23529411764705882,
  'bert_score': 0.5082954168319702},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.75,
  'translation_length': 7,
  'reference_length': 4,
  'bleu1': 0.14285714285714285,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.4,
  'rouge2': 0.0,
  'rougeL': 0.2,
  'rougeLsum': 0.2,
  'bert_score': 0.7906472086906433},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 7,
  'reference_length': 7,
  'bleu1': 0.42857142857142855,
  'bleu2': 0.16666666666666666,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3333333333333333,
  'rouge2': 0.20000000000000004,
  'rougeL': 0.3333333333333333,
  'rougeLsum': 0.3333333333333333,
  'bert_score': 0.40415284037590027},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.2222222222222223,
  'translation_length': 11,
  'reference_length': 9,
  'bleu1': 0.09090909090909091,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.48828473687171936},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 5,
  'reference_length': 5,
  'bleu1': 0.8,
  'bleu2': 0.5,
  'bleu3': 0.3333333333333333,
  'bleu4': 0.0,
  'rouge1': 0.75,
  'rouge2': 0.6666666666666666,
  'rougeL': 0.75,
  'rougeLsum': 0.75,
  'bert_score': 0.903544008731842},
 {'bleu': 0.0,
  'brevity_penalty': 0.846481724890614,
  'length_ratio': 0.8571428571428571,
  'translation_length': 6,
  'reference_length': 7,
  'bleu1': 0.16666666666666666,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.14285714285714285,
  'rouge2': 0.0,
  'rougeL': 0.14285714285714285,
  'rougeLsum': 0.14285714285714285,
  'bert_score': 0.5368502140045166},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.6666666666666667,
  'translation_length': 10,
  'reference_length': 6,
  'bleu1': 0.1,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.25,
  'rouge2': 0.14285714285714285,
  'rougeL': 0.25,
  'rougeLsum': 0.25,
  'bert_score': 0.3644120693206787},
 {'bleu': 0.0,
  'brevity_penalty': 0.8187307530779819,
  'length_ratio': 0.8333333333333334,
  'translation_length': 10,
  'reference_length': 12,
  'bleu1': 0.2,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.09523809523809525,
  'rouge2': 0.0,
  'rougeL': 0.09523809523809525,
  'rougeLsum': 0.09523809523809525,
  'bert_score': 0.26714932918548584},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.75,
  'translation_length': 11,
  'reference_length': 4,
  'bleu1': 0.2727272727272727,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.30769230769230765,
  'rouge2': 0.0,
  'rougeL': 0.30769230769230765,
  'rougeLsum': 0.30769230769230765,
  'bert_score': 0.5781902074813843},
 {'bleu': 0.0,
  'brevity_penalty': 0.6065306597126334,
  'length_ratio': 0.6666666666666666,
  'translation_length': 6,
  'reference_length': 9,
  'bleu1': 0.3333333333333333,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3076923076923077,
  'rouge2': 0.0,
  'rougeL': 0.15384615384615385,
  'rougeLsum': 0.15384615384615385,
  'bert_score': 0.374541312456131},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 3.142857142857143,
  'translation_length': 22,
  'reference_length': 7,
  'bleu1': 0.09090909090909091,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.13793103448275862,
  'rouge2': 0.0,
  'rougeL': 0.13793103448275862,
  'rougeLsum': 0.13793103448275862,
  'bert_score': 0.37928128242492676},
 {'bleu': 0.0,
  'brevity_penalty': 0.7165313105737893,
  'length_ratio': 0.75,
  'translation_length': 9,
  'reference_length': 12,
  'bleu1': 0.2222222222222222,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.11111111111111112,
  'rouge2': 0.0,
  'rougeL': 0.11111111111111112,
  'rougeLsum': 0.11111111111111112,
  'bert_score': 0.6776925325393677},
 {'bleu': 0.6434588841607617,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 7,
  'reference_length': 7,
  'bleu1': 0.8571428571428571,
  'bleu2': 0.6666666666666666,
  'bleu3': 0.6,
  'bleu4': 0.5,
  'rouge1': 0.8333333333333334,
  'rouge2': 0.6,
  'rougeL': 0.8333333333333334,
  'rougeLsum': 0.8333333333333334,
  'bert_score': 0.986339807510376},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.8333333333333333,
  'translation_length': 11,
  'reference_length': 6,
  'bleu1': 0.5454545454545454,
  'bleu2': 0.3,
  'bleu3': 0.1111111111111111,
  'bleu4': 0.0,
  'rouge1': 0.625,
  'rouge2': 0.28571428571428575,
  'rougeL': 0.625,
  'rougeLsum': 0.625,
  'bert_score': 0.8297522068023682},
 {'bleu': 0.0,
  'brevity_penalty': 0.5647181220077593,
  'length_ratio': 0.6363636363636364,
  'translation_length': 7,
  'reference_length': 11,
  'bleu1': 0.8571428571428571,
  'bleu2': 0.5,
  'bleu3': 0.2,
  'bleu4': 0.0,
  'rouge1': 0.625,
  'rouge2': 0.42857142857142855,
  'rougeL': 0.625,
  'rougeLsum': 0.625,
  'bert_score': 0.7921711206436157},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.2,
  'translation_length': 11,
  'reference_length': 5,
  'bleu1': 0.18181818181818182,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.4285714285714285,
  'rouge2': 0.0,
  'rougeL': 0.28571428571428575,
  'rougeLsum': 0.28571428571428575,
  'bert_score': 0.5147885680198669},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.6666666666666667,
  'translation_length': 15,
  'reference_length': 9,
  'bleu1': 0.26666666666666666,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3,
  'rouge2': 0.0,
  'rougeL': 0.3,
  'rougeLsum': 0.3,
  'bert_score': 0.6331424713134766},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.75,
  'translation_length': 14,
  'reference_length': 8,
  'bleu1': 0.2857142857142857,
  'bleu2': 0.07692307692307693,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.4,
  'rouge2': 0.0,
  'rougeL': 0.4,
  'rougeLsum': 0.4,
  'bert_score': 0.8503792881965637},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 3.3333333333333335,
  'translation_length': 20,
  'reference_length': 6,
  'bleu1': 0.1,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.08333333333333333,
  'rouge2': 0.0,
  'rougeL': 0.08333333333333333,
  'rougeLsum': 0.08333333333333333,
  'bert_score': 0.5131783485412598},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.5,
  'translation_length': 10,
  'reference_length': 4,
  'bleu1': 0.0,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.3318077325820923},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.3333333333333333,
  'translation_length': 8,
  'reference_length': 6,
  'bleu1': 0.25,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.16666666666666666,
  'rouge2': 0.0,
  'rougeL': 0.16666666666666666,
  'rougeLsum': 0.16666666666666666,
  'bert_score': 0.43696749210357666},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.4285714285714286,
  'translation_length': 10,
  'reference_length': 7,
  'bleu1': 0.5,
  'bleu2': 0.1111111111111111,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.5333333333333333,
  'rouge2': 0.15384615384615385,
  'rougeL': 0.5333333333333333,
  'rougeLsum': 0.5333333333333333,
  'bert_score': 0.6204923391342163},
 {'bleu': 0.0,
  'brevity_penalty': 0.6065306597126334,
  'length_ratio': 0.6666666666666666,
  'translation_length': 6,
  'reference_length': 9,
  'bleu1': 0.5,
  'bleu2': 0.2,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3076923076923077,
  'rouge2': 0.18181818181818182,
  'rougeL': 0.3076923076923077,
  'rougeLsum': 0.3076923076923077,
  'bert_score': 0.3426143527030945},
 {'bleu': 1.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 4,
  'reference_length': 4,
  'bleu1': 1.0,
  'bleu2': 1.0,
  'bleu3': 1.0,
  'bleu4': 1.0,
  'rouge1': 1.0,
  'rouge2': 1.0,
  'rougeL': 1.0,
  'rougeLsum': 1.0,
  'bert_score': 1.0},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 6,
  'reference_length': 6,
  'bleu1': 0.16666666666666666,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.3856484889984131},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 5,
  'reference_length': 5,
  'bleu1': 0.4,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.25,
  'rouge2': 0.0,
  'rougeL': 0.25,
  'rougeLsum': 0.25,
  'bert_score': 0.4622570872306824},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.2857142857142858,
  'translation_length': 9,
  'reference_length': 7,
  'bleu1': 0.5555555555555556,
  'bleu2': 0.25,
  'bleu3': 0.14285714285714285,
  'bleu4': 0.0,
  'rouge1': 0.5714285714285715,
  'rouge2': 0.3333333333333333,
  'rougeL': 0.5714285714285715,
  'rougeLsum': 0.5714285714285715,
  'bert_score': 0.5768518447875977},
 {'bleu': 1.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 5,
  'reference_length': 5,
  'bleu1': 1.0,
  'bleu2': 1.0,
  'bleu3': 1.0,
  'bleu4': 1.0,
  'rouge1': 1.0,
  'rouge2': 1.0,
  'rougeL': 1.0,
  'rougeLsum': 1.0,
  'bert_score': 1.000000238418579},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.5,
  'translation_length': 9,
  'reference_length': 6,
  'bleu1': 0.3333333333333333,
  'bleu2': 0.125,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3076923076923077,
  'rouge2': 0.18181818181818182,
  'rougeL': 0.3076923076923077,
  'rougeLsum': 0.3076923076923077,
  'bert_score': 0.1909385621547699},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.75,
  'translation_length': 11,
  'reference_length': 4,
  'bleu1': 0.09090909090909091,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.20455440878868103},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.3333333333333333,
  'translation_length': 8,
  'reference_length': 6,
  'bleu1': 0.125,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.2290404736995697},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.0,
  'translation_length': 10,
  'reference_length': 5,
  'bleu1': 0.4,
  'bleu2': 0.1111111111111111,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.46153846153846156,
  'rouge2': 0.18181818181818182,
  'rougeL': 0.46153846153846156,
  'rougeLsum': 0.46153846153846156,
  'bert_score': 0.8022259473800659},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.1428571428571428,
  'translation_length': 8,
  'reference_length': 7,
  'bleu1': 0.25,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.15384615384615383,
  'rouge2': 0.0,
  'rougeL': 0.15384615384615383,
  'rougeLsum': 0.15384615384615383,
  'bert_score': 0.4523516893386841},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.5,
  'translation_length': 10,
  'reference_length': 4,
  'bleu1': 0.4,
  'bleu2': 0.1111111111111111,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.5,
  'rouge2': 0.2,
  'rougeL': 0.5,
  'rougeLsum': 0.5,
  'bert_score': 0.8282537460327148},
 {'bleu': 0.36889397323344053,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 9,
  'reference_length': 9,
  'bleu1': 0.7777777777777778,
  'bleu2': 0.5,
  'bleu3': 0.2857142857142857,
  'bleu4': 0.16666666666666666,
  'rouge1': 0.75,
  'rouge2': 0.42857142857142855,
  'rougeL': 0.75,
  'rougeLsum': 0.75,
  'bert_score': 0.9648038744926453},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.6666666666666667,
  'translation_length': 10,
  'reference_length': 6,
  'bleu1': 0.5,
  'bleu2': 0.2222222222222222,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.5714285714285714,
  'rouge2': 0.3333333333333333,
  'rougeL': 0.5714285714285714,
  'rougeLsum': 0.5714285714285714,
  'bert_score': 0.8426656723022461},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.1666666666666667,
  'translation_length': 7,
  'reference_length': 6,
  'bleu1': 0.42857142857142855,
  'bleu2': 0.16666666666666666,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3636363636363636,
  'rouge2': 0.22222222222222224,
  'rougeL': 0.3636363636363636,
  'rougeLsum': 0.3636363636363636,
  'bert_score': 0.41334038972854614},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.25,
  'translation_length': 9,
  'reference_length': 4,
  'bleu1': 0.2222222222222222,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.18181818181818182,
  'rouge2': 0.0,
  'rougeL': 0.18181818181818182,
  'rougeLsum': 0.18181818181818182,
  'bert_score': 0.524726152420044},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 9,
  'reference_length': 9,
  'bleu1': 0.4444444444444444,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.35294117647058826,
  'rouge2': 0.0,
  'rougeL': 0.35294117647058826,
  'rougeLsum': 0.35294117647058826,
  'bert_score': 0.7519341707229614},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.8333333333333333,
  'translation_length': 11,
  'reference_length': 6,
  'bleu1': 0.36363636363636365,
  'bleu2': 0.1,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.4705882352941177,
  'rouge2': 0.26666666666666666,
  'rougeL': 0.4705882352941177,
  'rougeLsum': 0.4705882352941177,
  'bert_score': 0.735360860824585},
 {'bleu': 0.3266828640925502,
  'brevity_penalty': 0.751477293075286,
  'length_ratio': 0.7777777777777778,
  'translation_length': 7,
  'reference_length': 9,
  'bleu1': 0.7142857142857143,
  'bleu2': 0.5,
  'bleu3': 0.4,
  'bleu4': 0.25,
  'rouge1': 0.5714285714285715,
  'rouge2': 0.3333333333333333,
  'rougeL': 0.5714285714285715,
  'rougeLsum': 0.5714285714285715,
  'bert_score': 0.8223886489868164},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.375,
  'translation_length': 11,
  'reference_length': 8,
  'bleu1': 0.36363636363636365,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.3529411764705882,
  'rouge2': 0.0,
  'rougeL': 0.23529411764705882,
  'rougeLsum': 0.23529411764705882,
  'bert_score': 0.6995143890380859},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 2.0,
  'translation_length': 18,
  'reference_length': 9,
  'bleu1': 0.2222222222222222,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.31999999999999995,
  'rouge2': 0.0,
  'rougeL': 0.15999999999999998,
  'rougeLsum': 0.15999999999999998,
  'bert_score': 0.8477193117141724},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.4,
  'translation_length': 7,
  'reference_length': 5,
  'bleu1': 0.2857142857142857,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.1818181818181818,
  'rouge2': 0.0,
  'rougeL': 0.1818181818181818,
  'rougeLsum': 0.1818181818181818,
  'bert_score': 0.3178119957447052},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.25,
  'translation_length': 5,
  'reference_length': 4,
  'bleu1': 0.6,
  'bleu2': 0.25,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.5714285714285715,
  'rouge2': 0.0,
  'rougeL': 0.5714285714285715,
  'rougeLsum': 0.5714285714285715,
  'bert_score': 0.9332402348518372},
 {'bleu': 0.0,
  'brevity_penalty': 0.8187307530779819,
  'length_ratio': 0.8333333333333334,
  'translation_length': 5,
  'reference_length': 6,
  'bleu1': 0.8,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.6666666666666665,
  'rouge2': 0.0,
  'rougeL': 0.4444444444444445,
  'rougeLsum': 0.4444444444444445,
  'bert_score': 0.9378310441970825},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.5,
  'translation_length': 6,
  'reference_length': 4,
  'bleu1': 0.3333333333333333,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.25,
  'rouge2': 0.0,
  'rougeL': 0.25,
  'rougeLsum': 0.25,
  'bert_score': 0.3614546060562134},
 {'bleu': 0.3655552228545123,
  'brevity_penalty': 1.0,
  'length_ratio': 1.3333333333333333,
  'translation_length': 8,
  'reference_length': 6,
  'bleu1': 0.625,
  'bleu2': 0.42857142857142855,
  'bleu3': 0.3333333333333333,
  'bleu4': 0.2,
  'rouge1': 0.6666666666666666,
  'rouge2': 0.6,
  'rougeL': 0.6666666666666666,
  'rougeLsum': 0.6666666666666666,
  'bert_score': 0.44615209102630615},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 13,
  'reference_length': 13,
  'bleu1': 0.23076923076923078,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.1818181818181818,
  'rouge2': 0.0,
  'rougeL': 0.1818181818181818,
  'rougeLsum': 0.1818181818181818,
  'bert_score': 0.715283989906311},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.0,
  'translation_length': 5,
  'reference_length': 5,
  'bleu1': 0.6,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.5,
  'rouge2': 0.0,
  'rougeL': 0.25,
  'rougeLsum': 0.25,
  'bert_score': 0.8687304258346558},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.8333333333333333,
  'translation_length': 11,
  'reference_length': 6,
  'bleu1': 0.09090909090909091,
  'bleu2': 0.0,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.0,
  'rouge2': 0.0,
  'rougeL': 0.0,
  'rougeLsum': 0.0,
  'bert_score': 0.2561178207397461},
 {'bleu': 0.0,
  'brevity_penalty': 1.0,
  'length_ratio': 1.3333333333333333,
  'translation_length': 8,
  'reference_length': 6,
  'bleu1': 0.625,
  'bleu2': 0.14285714285714285,
  'bleu3': 0.0,
  'bleu4': 0.0,
  'rouge1': 0.6666666666666666,
  'rouge2': 0.2,
  'rougeL': 0.6666666666666666,

In [48]:
import pandas as pd
import numpy as np
from scipy import stats

def run_ttests(all_scores):
    """
    Run paired t-tests across models for multiple score metrics.
    all_scores[0] is treated as baseline.
    """
    
    def significance_label(p):
        return "significant" if p < 0.05 else "not significant"

    def cohens_d_paired(x, y):
        diff = np.array(x) - np.array(y)
        return diff.mean() / diff.std(ddof=1)

    score_list = ['bleu1', 'bleu2', 'bleu3', 'bleu4',
                  'rouge1', 'rouge2', 'rougeL', 'bert_score']

    rows = []

    baseline = all_scores[0]
    baseline_label = baseline['column']

    for score_name in score_list:
        baseline_scores = [s[score_name] for s in baseline['scores']]

        for item in all_scores[1:]:
            current_scores = [s[score_name] for s in item['scores']]

            # paired differences
            diffs = np.array(baseline_scores) - np.array(current_scores)
            sd_diff = diffs.std(ddof=1)

            # paired t-test
            t_stat, p_value = stats.ttest_rel(baseline_scores, current_scores)

            # Cohen’s d
            d = cohens_d_paired(baseline_scores, current_scores)

            rows.append({
                "score": score_name,
                "baseline": baseline_label,
                "comparison": item['column'],
                "cohens_d": d,
                "sd_diff": sd_diff,
                "t_stat": t_stat,
                "p_value": p_value,
                "significance": significance_label(p_value),
            })

    return pd.DataFrame(rows)

In [49]:
df_ttest = run_ttests(all_scores)
df_ttest

,score,baseline,comparison,cohens_d,sd_diff,t_stat,p_value,significance
0,bleu1,baseline,v1-12-SQuAD-id.jsonl,0.229524,0.250037,17.671839,3.774255e-68,significant
1,bleu1,baseline,v1-42-SQuAD-id.jsonl,-0.158240,0.218931,-12.183469,9.615812e-34,significant
2,bleu1,baseline,v1-72-SQuAD-id.jsonl,-0.118630,0.228322,-9.133773,8.909948e-20,significant
3,bleu1,baseline,v2-12-SQuAD-id.jsonl,-0.202597,0.220090,-15.598621,8.628058e-54,significant
4,bleu1,baseline,v2-42-SQuAD-id.jsonl,-0.199902,0.220740,-15.391187,1.918669e-52,significant
5,bleu1,baseline,v2-72-SQuAD-id.jsonl,-0.235131,0.221372,-18.103544,2.426828e-71,significant
6,bleu2,baseline,v1-12-SQuAD-id.jsonl,0.061880,0.201752,4.764356,1.939744e-06,significant
7,bleu2,baseline,v1-42-SQuAD-id.jsonl,-0.168005,0.197083,-12.935259,9.199346e-38,significant
8,bleu2,baseline,v1-72-SQuAD-id.jsonl,-0.151281,0.204150,-11.647669,5.123781e-31,significant
9,bleu2,baseline,v2-12-SQuAD-id.jsonl,-0.188780,0.199951,-14.534873,4.663109e-47,significant
10,bleu2,baseline,v2-42-SQuAD-id.jsonl,-0.176955,0.200885,-13.624385,1.209467e-41,significant
11,bleu2,baseline,v2-72-SQuAD-id.jsonl,-0.203824,0.202112,-15.693125,2.073639e-54,significant
12,bleu3,baseline,v1-12-SQuAD-id.jsonl,0.032331,0.168522,2.489274,1.282764e-02,significant
13,bleu3,baseline,v1-42-SQuAD-id.jsonl,-0.137157,0.168787,-10.560229,7.718999e-26,significant
14,bleu3,baseline,v1-72-SQuAD-id.jsonl,-0.120774,0.177379,-9.298818,1.954825e-20,significant
15,bleu3,baseline,v2-12-SQuAD-id.jsonl,-0.143794,0.172822,-11.071211,3.266374e-28,significant
16,bleu3,baseline,v2-42-SQuAD-id.jsonl,-0.133609,0.173482,-10.287015,1.297450e-24,significant
17,bleu3,baseline,v2-72-SQuAD-id.jsonl,-0.147325,0.176514,-11.343099,1.614501e-29,significant
18,bleu4,baseline,v1-12-SQuAD-id.jsonl,0.026383,0.148352,2.031319,4.226720e-02,significant
19,bleu4,baseline,v1-42-SQuAD-id.jsonl,-0.104891,0.149807,-8.075893,8.048033e-16,significant
20,bleu4,baseline,v1-72-SQuAD-id.jsonl,-0.093899,0.160390,-7.229612,5.455385e-13,significant
21,bleu4,baseline,v2-12-SQuAD-id.jsonl,-0.100037,0.154866,-7.702186,1.557788e-14,significant
22,bleu4,baseline,v2-42-SQuAD-id.jsonl,-0.098410,0.154705,-7.576936,4.081682e-14,significant
23,bleu4,baseline,v2-72-SQuAD-id.jsonl,-0.103655,0.160251,-7.980773,1.732665e-15,significant
24,rouge1,baseline,v1-12-SQuAD-id.jsonl,0.038510,0.235500,2.965050,3.038395e-03,significant
25,rouge1,baseline,v1-42-SQuAD-id.jsonl,-0.228445,0.217445,-17.588799,1.523696e-67,significant
26,rouge1,baseline,v1-72-SQuAD-id.jsonl,-0.212238,0.222672,-16.340974,9.562133e-59,significant
27,rouge1,baseline,v2-12-SQuAD-id.jsonl,-0.245096,0.218030,-18.870813,3.497689e-77,significant
28,rouge1,baseline,v2-42-SQuAD-id.jsonl,-0.244932,0.221047,-18.858170,4.382928e-77,significant
29,rouge1,baseline,v2-72-SQuAD-id.jsonl,-0.261559,0.220336,-20.138349,2.682972e-87,significant
30,rouge2,baseline,v1-12-SQuAD-id.jsonl,-0.017849,0.196990,-1.374280,1.694068e-01,not significant
31,rouge2,baseline,v1-42-SQuAD-id.jsonl,-0.198181,0.193639,-15.258685,1.364092e-51,significant
32,rouge2,baseline,v1-72-SQuAD-id.jsonl,-0.192181,0.200454,-14.796662,1.127858e-48,significant
33,rouge2,baseline,v2-12-SQuAD-id.jsonl,-0.200934,0.198646,-15.470579,5.879937e-53,significant
34,rouge2,baseline,v2-42-SQuAD-id.jsonl,-0.192181,0.199274,-14.796690,1.127402e-48,significant
35,rouge2,baseline,v2-72-SQuAD-id.jsonl,-0.211716,0.198904,-16.300727,1.797122e-58,significant
36,rougeL,baseline,v1-12-SQuAD-id.jsonl,0.078711,0.228793,6.060229,1.442918e-09,significant
37,rougeL,baseline,v1-42-SQuAD-id.jsonl,-0.206218,0.213328,-15.877445,1.256872e-55,significant
38,rougeL,baseline,v1-72-SQuAD-id.jsonl,-0.184317,0.219908,-14.191248,5.623090e-45,significant
39,rougeL,baseline,v2-12-SQuAD-id.jsonl,-0.229139,0.213835,-17.642203,6.214710e-68,significant
40,rougeL,baseline,v2-42-SQuAD-id.jsonl,-0.226169,0.215871,-17.413527,2.842641e-66,significant
41,rougeL,baseline,v2-72-SQuAD-id.jsonl,-0.246204,0.214738,-18.956077,7.611122e-78,significant
42,bert_score,baseline,v1-12-SQuAD-id.jsonl,-0.167662,0.208529,-12.908920,1.283421e-37,significant
43,bert_score,baseline,v1-42-SQuAD-id.jsonl,-0.257959,0.205765,-19.861137,4.895608e-85,significant
44,bert_score,baseline,v1-72-SQuAD-id.jsonl,-0.255461,0.204627,-19.668827,1.747536e-83,significant
45,bert_score,baseline,v2-12-SQuAD-id.jsonl,-0.258071,0.206398,-19.869828,4.162254e-85,significant
46,bert_score,baseline,v2-42-SQuAD-id.jsonl,-0.255484,0.208648,-19.670573,1.691968e-83,significant
47,bert_score,baseline,v2-72-SQuAD-id.jsonl,-0.256562,0.207014,-19.753623,3.626174e-84,significant

In [51]:
df_ttest.to_excel('ttest-results-squad.xlsx', index=False)

In [52]:
df_ttest_tydiqa = run_ttests(all_scores_tydiqa)
df_ttest_tydiqa

,score,baseline,comparison,cohens_d,sd_diff,t_stat,p_value,significance
0,bleu1,baseline,v1-12-TydiQA-id.jsonl,-0.158093,0.304634,-3.757834,1.892322e-04,significant
1,bleu1,baseline,v1-42-TydiQA-id.jsonl,0.139317,0.333688,3.311517,9.872705e-04,significant
2,bleu1,baseline,v1-72-TydiQA-id.jsonl,-0.178645,0.302516,-4.246354,2.540997e-05,significant
3,bleu1,baseline,v2-12-TydiQA-id.jsonl,-0.054169,0.309818,-1.287571,1.984233e-01,not significant
4,bleu1,baseline,v2-42-TydiQA-id.jsonl,-0.131335,0.311075,-3.121789,1.889627e-03,significant
5,bleu1,baseline,v2-72-TydiQA-id.jsonl,0.008465,0.332461,0.201202,8.406133e-01,not significant
6,bleu2,baseline,v1-12-TydiQA-id.jsonl,-0.185224,0.290105,-4.402730,1.279046e-05,significant
7,bleu2,baseline,v1-42-TydiQA-id.jsonl,0.015261,0.310212,0.362761,7.169194e-01,not significant
8,bleu2,baseline,v1-72-TydiQA-id.jsonl,-0.225773,0.285119,-5.366553,1.173748e-07,significant
9,bleu2,baseline,v2-12-TydiQA-id.jsonl,-0.124129,0.285852,-2.950516,3.304178e-03,significant
10,bleu2,baseline,v2-42-TydiQA-id.jsonl,-0.172883,0.295146,-4.109372,4.556222e-05,significant
11,bleu2,baseline,v2-72-TydiQA-id.jsonl,-0.073977,0.302868,-1.758417,7.921892e-02,not significant
12,bleu3,baseline,v1-12-TydiQA-id.jsonl,-0.128543,0.261683,-3.055421,2.353689e-03,significant
13,bleu3,baseline,v1-42-TydiQA-id.jsonl,0.010569,0.282071,0.251232,8.017264e-01,not significant
14,bleu3,baseline,v1-72-TydiQA-id.jsonl,-0.168668,0.274001,-4.009184,6.912090e-05,significant
15,bleu3,baseline,v2-12-TydiQA-id.jsonl,-0.076091,0.265840,-1.808674,7.103409e-02,not significant
16,bleu3,baseline,v2-42-TydiQA-id.jsonl,-0.140898,0.273107,-3.349096,8.648864e-04,significant
17,bleu3,baseline,v2-72-TydiQA-id.jsonl,-0.058134,0.276045,-1.381824,1.675728e-01,not significant
18,bleu4,baseline,v1-12-TydiQA-id.jsonl,-0.065617,0.236475,-1.559707,1.193900e-01,not significant
19,bleu4,baseline,v1-42-TydiQA-id.jsonl,0.013155,0.255789,0.312694,7.546286e-01,not significant
20,bleu4,baseline,v1-72-TydiQA-id.jsonl,-0.116710,0.259286,-2.774164,5.717700e-03,significant
21,bleu4,baseline,v2-12-TydiQA-id.jsonl,-0.053913,0.243912,-1.281498,2.005454e-01,not significant
22,bleu4,baseline,v2-42-TydiQA-id.jsonl,-0.111114,0.249197,-2.641149,8.491617e-03,significant
23,bleu4,baseline,v2-72-TydiQA-id.jsonl,-0.029434,0.252913,-0.699630,4.844471e-01,not significant
24,rouge1,baseline,v1-12-TydiQA-id.jsonl,-0.289920,0.315320,-6.891327,1.483032e-11,significant
25,rouge1,baseline,v1-42-TydiQA-id.jsonl,0.012709,0.341968,0.302098,7.626890e-01,not significant
26,rouge1,baseline,v1-72-TydiQA-id.jsonl,-0.289723,0.308771,-6.886648,1.528709e-11,significant
27,rouge1,baseline,v2-12-TydiQA-id.jsonl,-0.165669,0.320033,-3.937901,9.248744e-05,significant
28,rouge1,baseline,v2-42-TydiQA-id.jsonl,-0.221299,0.323525,-5.260213,2.046513e-07,significant
29,rouge1,baseline,v2-72-TydiQA-id.jsonl,-0.110527,0.344427,-2.627207,8.843063e-03,significant
30,rouge2,baseline,v1-12-TydiQA-id.jsonl,-0.207715,0.296162,-4.937331,1.044643e-06,significant
31,rouge2,baseline,v1-42-TydiQA-id.jsonl,0.023766,0.300498,0.564912,5.723584e-01,not significant
32,rouge2,baseline,v1-72-TydiQA-id.jsonl,-0.221537,0.286244,-5.265863,1.987416e-07,significant
33,rouge2,baseline,v2-12-TydiQA-id.jsonl,-0.125283,0.292456,-2.977950,3.026538e-03,significant
34,rouge2,baseline,v2-42-TydiQA-id.jsonl,-0.172838,0.305128,-4.108305,4.576685e-05,significant
35,rouge2,baseline,v2-72-TydiQA-id.jsonl,-0.073974,0.314277,-1.758335,7.923293e-02,not significant
36,rougeL,baseline,v1-12-TydiQA-id.jsonl,-0.277042,0.315605,-6.585218,1.041487e-10,significant
37,rougeL,baseline,v1-42-TydiQA-id.jsonl,0.028172,0.341306,0.669632,5.033667e-01,not significant
38,rougeL,baseline,v1-72-TydiQA-id.jsonl,-0.278043,0.306694,-6.609001,8.974415e-11,significant
39,rougeL,baseline,v2-12-TydiQA-id.jsonl,-0.157169,0.317813,-3.735862,2.061055e-04,significant
40,rougeL,baseline,v2-42-TydiQA-id.jsonl,-0.209777,0.321450,-4.986352,8.202230e-07,significant
41,rougeL,baseline,v2-72-TydiQA-id.jsonl,-0.096693,0.341557,-2.298361,2.190614e-02,significant
42,bert_score,baseline,v1-12-TydiQA-id.jsonl,-0.339391,0.270022,-8.067227,4.344525e-15,significant
43,bert_score,baseline,v1-42-TydiQA-id.jsonl,-0.044333,0.300052,-1.053789,2.924308e-01,not significant
44,bert_score,baseline,v1-72-TydiQA-id.jsonl,-0.334375,0.264009,-7.948012,1.037111e-14,significant
45,bert_score,baseline,v2-12-TydiQA-id.jsonl,-0.250431,0.270744,-5.952689,4.638167e-09,significant
46,bert_score,baseline,v2-42-TydiQA-id.jsonl,-0.294851,0.269805,-7.008525,6.899948e-12,significant
47,bert_score,baseline,v2-72-TydiQA-id.jsonl,-0.189576,0.294298,-4.506170,8.028963e-06,significant

In [53]:
df_ttest_tydiqa.to_excel('ttest-results-tydiqa.xlsx', index=False)